import { MathQuestion } from "./mathQuestionTypes";

export const GRADE_6_QUESTIONS: MathQuestion[] = [
  // --- TÌM X & PHƯƠNG TRÌNH BẬC NHẤT (1 - 30) ---
  {
    id: "g6_001",
    problemStr: "Tìm x: 2x - 4 = 6",
    correctAnswer: 5,
    emojiAnalogy: "2x = 6 + 4 = 10 ➡️ x = 10 : 2 = 5 💡",
    explanation: "Chuyển vế: 2x = 6 + 4 = 10. Do đó x = 10 : 2 = 5!",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_002",
    problemStr: "Tìm x: 3x + 1 = 10",
    correctAnswer: 3,
    emojiAnalogy: "3x = 10 - 1 = 9 ➡️ x = 9 : 3 = 3 ✏️",
    explanation: "3x = 9, vậy x = 9 : 3 = 3.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_003",
    problemStr: "Tìm x: 4x - 8 = 12",
    correctAnswer: 5,
    emojiAnalogy: "4x = 20 ➡️ x = 20 : 4 = 5 🎯",
    explanation: "4x = 12 + 8 = 20 ➡️ x = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_004",
    problemStr: "Tìm x: 2x + 6 = 18",
    correctAnswer: 6,
    emojiAnalogy: "2x = 18 - 6 = 12 ➡️ x = 6 🌟",
    explanation: "2x = 12 ➡️ x = 12 : 2 = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_005",
    problemStr: "Tìm x: 5x - 10 = 25",
    correctAnswer: 7,
    emojiAnalogy: "5x = 35 ➡️ x = 35 : 5 = 7 🚀",
    explanation: "5x = 25 + 10 = 35 ➡️ x = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_006",
    problemStr: "Tìm x: 3x - 6 = 15",
    correctAnswer: 7,
    emojiAnalogy: "3x = 21 ➡️ x = 21 : 3 = 7 🔑",
    explanation: "3x = 15 + 6 = 21 ➡️ x = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_007",
    problemStr: "Tìm x: 4x + 4 = 36",
    correctAnswer: 8,
    emojiAnalogy: "4x = 32 ➡️ x = 32 : 4 = 8 ⚡",
    explanation: "4x = 36 - 4 = 32 ➡️ x = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_008",
    problemStr: "Tìm x: 6x - 12 = 42",
    correctAnswer: 9,
    emojiAnalogy: "6x = 54 ➡️ x = 54 : 6 = 9 💎",
    explanation: "6x = 42 + 12 = 54 ➡️ x = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_009",
    problemStr: "Tìm x: 2x + 1 = 9",
    correctAnswer: 4,
    emojiAnalogy: "2x = 8 ➡️ x = 4 🍏",
    explanation: "2x = 8 ➡️ x = 4.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_010",
    problemStr: "Tìm x: 5x + 10 = 50",
    correctAnswer: 8,
    emojiAnalogy: "5x = 40 ➡️ x = 8 🎈",
    explanation: "5x = 40 ➡️ x = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_011",
    problemStr: "Tìm x: 3x + 9 = 30",
    correctAnswer: 7,
    emojiAnalogy: "3x = 21 ➡️ x = 7 🌸",
    explanation: "3x = 30 - 9 = 21 ➡️ x = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_012",
    problemStr: "Tìm x: 7x - 7 = 49",
    correctAnswer: 8,
    emojiAnalogy: "7x = 56 ➡️ x = 8 🍉",
    explanation: "7x = 49 + 7 = 56 ➡️ x = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_013",
    problemStr: "Tìm x: 8x - 16 = 48",
    correctAnswer: 8,
    emojiAnalogy: "8x = 64 ➡️ x = 8 🍰",
    explanation: "8x = 64 ➡️ x = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_014",
    problemStr: "Tìm x: 9x - 18 = 63",
    correctAnswer: 9,
    emojiAnalogy: "9x = 81 ➡️ x = 9 🌟",
    explanation: "9x = 63 + 18 = 81 ➡️ x = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g6_015",
    problemStr: "Tìm x: 2(x + 3) = 14",
    correctAnswer: 4,
    emojiAnalogy: "x + 3 = 7 ➡️ x = 4 🍪",
    explanation: "x + 3 = 14 : 2 = 7 ➡️ x = 7 - 3 = 4.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_016",
    problemStr: "Tìm x: 3(x - 2) = 15",
    correctAnswer: 7,
    emojiAnalogy: "x - 2 = 5 ➡️ x = 7 🍓",
    explanation: "x - 2 = 15 : 3 = 5 ➡️ x = 5 + 2 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_017",
    problemStr: "Tìm x: 4(x + 1) = 28",
    correctAnswer: 6,
    emojiAnalogy: "x + 1 = 7 ➡️ x = 6 🚙",
    explanation: "x + 1 = 28 : 4 = 7 ➡️ x = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_018",
    problemStr: "Tìm x: 5(x - 1) = 40",
    correctAnswer: 9,
    emojiAnalogy: "x - 1 = 8 ➡️ x = 9 🎯",
    explanation: "x - 1 = 40 : 5 = 8 ➡️ x = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_019",
    problemStr: "Tìm x: 10x - 20 = 80",
    correctAnswer: 10,
    emojiAnalogy: "10x = 100 ➡️ x = 10 🔟",
    explanation: "10x = 100 ➡️ x = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_020",
    problemStr: "Tìm x: 2(x + 5) = 20",
    correctAnswer: 5,
    emojiAnalogy: "x + 5 = 10 ➡️ x = 5 🖐️",
    explanation: "x + 5 = 10 ➡️ x = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_021",
    problemStr: "Tìm x: 15 - 2x = 5",
    correctAnswer: 5,
    emojiAnalogy: "2x = 15 - 5 = 10 ➡️ x = 5 💡",
    explanation: "2x = 15 - 5 = 10 ➡️ x = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_022",
    problemStr: "Tìm x: 20 - 3x = 11",
    correctAnswer: 3,
    emojiAnalogy: "3x = 20 - 11 = 9 ➡️ x = 3 ✏️",
    explanation: "3x = 9 ➡️ x = 3.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_023",
    problemStr: "Tìm x: 30 - 4x = 6",
    correctAnswer: 6,
    emojiAnalogy: "4x = 24 ➡️ x = 6 🎲",
    explanation: "4x = 30 - 6 = 24 ➡️ x = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_024",
    problemStr: "Tìm x: 25 - 2x = 7",
    correctAnswer: 9,
    emojiAnalogy: "2x = 18 ➡️ x = 9 🚀",
    explanation: "2x = 25 - 7 = 18 ➡️ x = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_025",
    problemStr: "Tìm x: 18 - 5x = 3",
    correctAnswer: 3,
    emojiAnalogy: "5x = 15 ➡️ x = 3 🍉",
    explanation: "5x = 15 ➡️ x = 3.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_026",
    problemStr: "Tìm x: x² = 25 (với x > 0)",
    correctAnswer: 5,
    emojiAnalogy: "5² = 25 ➡️ x = 5 🖐️",
    explanation: "Vì x dương và 5 x 5 = 25 nên x = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_027",
    problemStr: "Tìm x: x² = 49 (với x > 0)",
    correctAnswer: 7,
    emojiAnalogy: "7² = 49 ➡️ x = 7 🌸",
    explanation: "7² = 49 ➡️ x = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_028",
    problemStr: "Tìm x: x² = 64 (với x > 0)",
    correctAnswer: 8,
    emojiAnalogy: "8² = 64 ➡️ x = 8 ⚡",
    explanation: "8² = 64 ➡️ x = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g6_029",
    problemStr: "Tìm x: x³ = 27",
    correctAnswer: 3,
    emojiAnalogy: "3 x 3 x 3 = 27 ➡️ x = 3 💎",
    explanation: "3³ = 27 nên x = 3.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g6_030",
    problemStr: "Tìm x: x³ = 64",
    correctAnswer: 4,
    emojiAnalogy: "4 x 4 x 4 = 64 ➡️ x = 4 📦",
    explanation: "4³ = 64 nên x = 4.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },

  // --- SỐ NGUYÊN & QUY TẮC DẤU (31 - 55) ---
  {
    id: "g6_031",
    problemStr: "Tính: 10 + (-3) = ?",
    correctAnswer: 7,
    emojiAnalogy: "10 - 3 = 7 ⚖️",
    explanation: "Cộng hai số nguyên khác dấu: 10 + (-3) = 10 - 3 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_032",
    problemStr: "Tính: 15 + (-7) = ?",
    correctAnswer: 8,
    emojiAnalogy: "15 - 7 = 8 🎯",
    explanation: "15 + (-7) = 15 - 7 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_033",
    problemStr: "Tính: (-4) + 10 = ?",
    correctAnswer: 6,
    emojiAnalogy: "10 - 4 = 6 🌟",
    explanation: "(-4) + 10 = 10 - 4 = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_034",
    problemStr: "Tính: 5 - (-4) = ?",
    correctAnswer: 9,
    emojiAnalogy: "5 + 4 = 9 🚀",
    explanation: "Trừ đi số âm bằng cộng số đối: 5 - (-4) = 5 + 4 = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_035",
    problemStr: "Tính: 2 - (-6) = ?",
    correctAnswer: 8,
    emojiAnalogy: "2 + 6 = 8 🎈",
    explanation: "2 - (-6) = 2 + 6 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_036",
    problemStr: "Tính: 3 - (-7) = ?",
    correctAnswer: 10,
    emojiAnalogy: "3 + 7 = 10 🔟",
    explanation: "3 - (-7) = 3 + 7 = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_037",
    problemStr: "Tính: (-2) x (-4) = ?",
    correctAnswer: 8,
    emojiAnalogy: "(-) x (-) = (+) ➡️ 2 x 4 = 8 ⚡",
    explanation: "Tích hai số nguyên âm là một số nguyên dương: (-2) x (-4) = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_038",
    problemStr: "Tính: (-3) x (-3) = ?",
    correctAnswer: 9,
    emojiAnalogy: "3 x 3 = 9 💎",
    explanation: "(-3) x (-3) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_039",
    problemStr: "Tính: (-18) : (-3) = ?",
    correctAnswer: 6,
    emojiAnalogy: "18 : 3 = 6 🎲",
    explanation: "Thương hai số nguyên âm mang dấu dương: (-18) : (-3) = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_040",
    problemStr: "Tính: (-28) : (-4) = ?",
    correctAnswer: 7,
    emojiAnalogy: "28 : 4 = 7 🌸",
    explanation: "(-28) : (-4) = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_041",
    problemStr: "Tính: (-36) : (-4) = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 🍉",
    explanation: "(-36) : (-4) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_042",
    problemStr: "Tính: (-50) : (-5) = ?",
    correctAnswer: 10,
    emojiAnalogy: "50 : 5 = 10 🔟",
    explanation: "(-50) : (-5) = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_043",
    problemStr: "Tính: 7 + (-7) = ?",
    correctAnswer: 0,
    emojiAnalogy: "Hai số đối nhau có tổng bằng 0 ✊",
    explanation: "Tổng hai số đối nhau luôn bằng 0 (Giơ nắm tay ✊)!",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_044",
    problemStr: "Tính: (-8) + 8 = ?",
    correctAnswer: 0,
    emojiAnalogy: "-8 + 8 = 0 ✊",
    explanation: "Tổng hai số đối bằng 0.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_045",
    problemStr: "Tính: 12 - 5 + (-2) = ?",
    correctAnswer: 5,
    emojiAnalogy: "7 + (-2) = 5 🖐️",
    explanation: "12 - 5 = 7, 7 + (-2) = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_046",
    problemStr: "Tính: 20 + (-8) - 5 = ?",
    correctAnswer: 7,
    emojiAnalogy: "12 - 5 = 7 🎯",
    explanation: "20 - 8 - 5 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_047",
    problemStr: "Tính: (-2) x (-2) x 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 x 2 = 8 ⚡",
    explanation: "(-2) x (-2) = 4, 4 x 2 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_048",
    problemStr: "Tính: 14 + (-5) = ?",
    correctAnswer: 9,
    emojiAnalogy: "14 - 5 = 9 🌟",
    explanation: "14 + (-5) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_049",
    problemStr: "Tính: (-10) + 16 = ?",
    correctAnswer: 6,
    emojiAnalogy: "16 - 10 = 6 🍓",
    explanation: "16 - 10 = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_050",
    problemStr: "Tính: 1 - (-6) = ?",
    correctAnswer: 7,
    emojiAnalogy: "1 + 6 = 7 🍒",
    explanation: "1 - (-6) = 1 + 6 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_051",
    problemStr: "Tính: 4 - (-4) = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 + 4 = 8 🍪",
    explanation: "4 - (-4) = 4 + 4 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_052",
    problemStr: "Tính: (-24) : (-4) = ?",
    correctAnswer: 6,
    emojiAnalogy: "24 : 4 = 6 🎲",
    explanation: "(-24) : (-4) = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_053",
    problemStr: "Tính: (-32) : (-4) = ?",
    correctAnswer: 8,
    emojiAnalogy: "32 : 4 = 8 🚙",
    explanation: "(-32) : (-4) = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_054",
    problemStr: "Tính: (-45) : (-5) = ?",
    correctAnswer: 9,
    emojiAnalogy: "45 : 5 = 9 🚀",
    explanation: "(-45) : (-5) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_055",
    problemStr: "Tính: (-2) x (-5) = ?",
    correctAnswer: 10,
    emojiAnalogy: "2 x 5 = 10 🔟",
    explanation: "(-2) x (-5) = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },

  // --- LŨY THỪA VỚI SỐ MŨ TỰ NHIÊN (56 - 75) ---
  {
    id: "g6_056",
    problemStr: "Lũy thừa: 2³ = ?",
    correctAnswer: 8,
    emojiAnalogy: "2³ = 2 x 2 x 2 = 8 ⚡",
    explanation: "2 mũ 3 là tích của 3 thừa số 2: 2 x 2 x 2 = 8!",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_057",
    problemStr: "Lũy thừa: 3² = ?",
    correctAnswer: 9,
    emojiAnalogy: "3² = 3 x 3 = 9 🌟",
    explanation: "3 bình phương bằng 3 x 3 = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_058",
    problemStr: "Lũy thừa: 2² = ?",
    correctAnswer: 4,
    emojiAnalogy: "2² = 2 x 2 = 4 🐣",
    explanation: "2 mũ 2 bằng 4.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_059",
    problemStr: "Lũy thừa: 7¹ = ?",
    correctAnswer: 7,
    emojiAnalogy: "7¹ = 7 🎯",
    explanation: "Bất kỳ số nào mũ 1 cũng bằng chính nó.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_060",
    problemStr: "Lũy thừa: 8¹ = ?",
    correctAnswer: 8,
    emojiAnalogy: "8¹ = 8 🎈",
    explanation: "8 mũ 1 bằng 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_061",
    problemStr: "Lũy thừa: 9¹ = ?",
    correctAnswer: 9,
    emojiAnalogy: "9¹ = 9 💎",
    explanation: "9 mũ 1 bằng 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_062",
    problemStr: "Lũy thừa: 10¹ = ?",
    correctAnswer: 10,
    emojiAnalogy: "10¹ = 10 🔟",
    explanation: "10 mũ 1 bằng 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_063",
    problemStr: "Lũy thừa: 2⁰ = ?",
    correctAnswer: 1,
    emojiAnalogy: "2⁰ = 1 ☝️",
    explanation: "Quy ước: a⁰ = 1 với mọi a khác 0.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_064",
    problemStr: "Lũy thừa: 5⁰ = ?",
    correctAnswer: 1,
    emojiAnalogy: "5⁰ = 1 🔑",
    explanation: "5 mũ 0 bằng 1.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_065",
    problemStr: "Lũy thừa: 10⁰ = ?",
    correctAnswer: 1,
    emojiAnalogy: "10⁰ = 1 🚪",
    explanation: "10 mũ 0 bằng 1.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_066",
    problemStr: "Tính: 3² - 2⁰ = ?",
    correctAnswer: 8,
    emojiAnalogy: "9 - 1 = 8 📐",
    explanation: "3² = 9; 2⁰ = 1 ➡️ 9 - 1 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_067",
    problemStr: "Tính: 2³ - 1 = ?",
    correctAnswer: 7,
    emojiAnalogy: "8 - 1 = 7 🌸",
    explanation: "2³ = 8, 8 - 1 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_068",
    problemStr: "Tính: 2³ + 2 = ?",
    correctAnswer: 10,
    emojiAnalogy: "8 + 2 = 10 🔟",
    explanation: "2³ = 8, 8 + 2 = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_069",
    problemStr: "Tính: 3² - 3 = ?",
    correctAnswer: 6,
    emojiAnalogy: "9 - 3 = 6 🎲",
    explanation: "3² = 9, 9 - 3 = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_070",
    problemStr: "Tính: 2⁴ - 10 = ?",
    correctAnswer: 6,
    emojiAnalogy: "16 - 10 = 6 🚙",
    explanation: "2⁴ = 16, 16 - 10 = 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_071",
    problemStr: "Tính: 2⁴ - 8 = ?",
    correctAnswer: 8,
    emojiAnalogy: "16 - 8 = 8 🍰",
    explanation: "2⁴ = 16, 16 - 8 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_072",
    problemStr: "Tính: 2⁴ - 7 = ?",
    correctAnswer: 9,
    emojiAnalogy: "16 - 7 = 9 🌟",
    explanation: "2⁴ = 16, 16 - 7 = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
  {
    id: "g6_073",
    problemStr: "Tính: 2² + 2² = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 + 4 = 8 🍪",
    explanation: "4 + 4 = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_074",
    problemStr: "Tính: 2² + 3 = ?",
    correctAnswer: 7,
    emojiAnalogy: "4 + 3 = 7 ⭐",
    explanation: "2² = 4, 4 + 3 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_075",
    problemStr: "Tính: 2³ : 2 = ?",
    correctAnswer: 4,
    emojiAnalogy: "8 : 2 = 4 🍏",
    explanation: "2³ = 8, 8 : 2 = 4 (hoặc 2³ : 2¹ = 2² = 4).",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },

  // --- ƯCLN & BCNN VÀ TẬP HỢP (76 - 100) ---
  {
    id: "g6_076",
    problemStr: "ƯCLN(12, 16) = ?",
    correctAnswer: 4,
    emojiAnalogy: "Ư(12) ∩ Ư(16) lớn nhất là 4 🧩",
    explanation: "12 = 2² x 3; 16 = 2⁴. Ước chung lớn nhất là 2² = 4!",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_077",
    problemStr: "BCNN(2, 3) = ?",
    correctAnswer: 6,
    emojiAnalogy: "BCNN(2, 3) = 6 🔄",
    explanation: "2 và 3 là hai số nguyên tố cùng nhau nên BCNN(2, 3) = 2 x 3 = 6!",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_078",
    problemStr: "ƯCLN(18, 24) = ?",
    correctAnswer: 6,
    emojiAnalogy: "18 = 6x3, 24 = 6x4 ➡️ ƯCLN = 6 💎",
    explanation: "Ước chung lớn nhất của 18 và 24 là 6.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_079",
    problemStr: "ƯCLN(21, 28) = ?",
    correctAnswer: 7,
    emojiAnalogy: "21 = 7x3, 28 = 7x4 ➡️ ƯCLN = 7 🌸",
    explanation: "Ước chung lớn nhất của 21 và 28 là 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_080",
    problemStr: "ƯCLN(16, 24) = ?",
    correctAnswer: 8,
    emojiAnalogy: "16 = 8x2, 24 = 8x3 ➡️ ƯCLN = 8 ⚡",
    explanation: "ƯCLN(16, 24) = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_081",
    problemStr: "ƯCLN(15, 20) = ?",
    correctAnswer: 5,
    emojiAnalogy: "15 = 5x3, 20 = 5x4 ➡️ ƯCLN = 5 🖐️",
    explanation: "ƯCLN(15, 20) = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_082",
    problemStr: "ƯCLN(18, 27) = ?",
    correctAnswer: 9,
    emojiAnalogy: "18 = 9x2, 27 = 9x3 ➡️ ƯCLN = 9 🌟",
    explanation: "ƯCLN(18, 27) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_083",
    problemStr: "ƯCLN(20, 30) = ?",
    correctAnswer: 10,
    emojiAnalogy: "20 = 10x2, 30 = 10x3 ➡️ ƯCLN = 10 🔟",
    explanation: "ƯCLN(20, 30) = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_084",
    problemStr: "BCNN(2, 4) = ?",
    correctAnswer: 4,
    emojiAnalogy: "Vì 4 chia hết cho 2 ➡️ BCNN = 4 ⏹️",
    explanation: "Khi số lớn chia hết cho số bé, BCNN chính là số lớn = 4.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_085",
    problemStr: "BCNN(2, 5) = ?",
    correctAnswer: 10,
    emojiAnalogy: "2 x 5 = 10 🔟",
    explanation: "2 và 5 là số nguyên tố ➡️ BCNN(2, 5) = 2 x 5 = 10.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_086",
    problemStr: "BCNN(4, 8) = ?",
    correctAnswer: 8,
    emojiAnalogy: "8 chia hết cho 4 ➡️ BCNN = 8 🍰",
    explanation: "BCNN(4, 8) = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_087",
    problemStr: "BCNN(3, 9) = ?",
    correctAnswer: 9,
    emojiAnalogy: "9 chia hết cho 3 ➡️ BCNN = 9 🚀",
    explanation: "BCNN(3, 9) = 9.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Dễ",
  },
  {
    id: "g6_088",
    problemStr: "ƯCLN(14, 21) = ?",
    correctAnswer: 7,
    emojiAnalogy: "ƯCLN(14, 21) = 7 🍒",
    explanation: "ƯCLN(14, 21) = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_089",
    problemStr: "ƯCLN(24, 32) = ?",
    correctAnswer: 8,
    emojiAnalogy: "24 = 8x3, 32 = 8x4 ➡️ ƯCLN = 8 🎯",
    explanation: "ƯCLN(24, 32) = 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_090",
    problemStr: "Số nguyên tố nhỏ nhất là?",
    correctAnswer: 2,
    emojiAnalogy: "Số nguyên tố chẵn duy nhất = 2 ✌️",
    explanation: "2 là số nguyên tố nhỏ nhất và cũng là số nguyên tố chẵn duy nhất.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_091",
    problemStr: "Số nguyên tố lẻ nhỏ nhất là?",
    correctAnswer: 3,
    emojiAnalogy: "3 là số nguyên tố lẻ nhỏ nhất 🔺",
    explanation: "Số nguyên tố lẻ nhỏ nhất là 3.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_092",
    problemStr: "Số hợp số nhỏ nhất là?",
    correctAnswer: 4,
    emojiAnalogy: "4 = 2 x 2 là hợp số nhỏ nhất ⏹️",
    explanation: "4 là số hợp số nhỏ nhất (có các ước 1, 2, 4).",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Dễ",
  },
  {
    id: "g6_093",
    problemStr: "Số phần tử của tập hợp A = {2, 3, 5, 7, 11} là?",
    correctAnswer: 5,
    emojiAnalogy: "Đếm: 5 phần tử 🖐️",
    explanation: "Tập hợp A có đúng 5 phần tử.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g6_094",
    problemStr: "Số phần tử của tập hợp {x ∈ N | 3 < x < 10} là?",
    correctAnswer: 6,
    emojiAnalogy: "{4, 5, 6, 7, 8, 9} = 6 phần tử 🎲",
    explanation: "Các số tự nhiên từ 4 đến 9 gồm 6 số.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Đếm hình & Toán đố",
    difficulty: "Trung bình",
  },
  {
    id: "g6_095",
    problemStr: "Số phần tử của tập hợp {x ∈ N | 1 ≤ x ≤ 8} là?",
    correctAnswer: 8,
    emojiAnalogy: "{1, 2, 3, 4, 5, 6, 7, 8} = 8 phần tử 🍪",
    explanation: "Tập hợp có 8 phần tử.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g6_096",
    problemStr: "Số ước tự nhiên của số 8 là?",
    correctAnswer: 4,
    emojiAnalogy: "Ư(8) = {1, 2, 4, 8} = 4 ước 💡",
    explanation: "Số 8 có 4 ước tự nhiên: 1, 2, 4, 8.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_097",
    problemStr: "Số ước tự nhiên của số 12 là?",
    correctAnswer: 6,
    emojiAnalogy: "Ư(12) = {1, 2, 3, 4, 6, 12} = 6 ước 🌟",
    explanation: "Số 12 có 6 ước tự nhiên: 1, 2, 3, 4, 6, 12.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_098",
    problemStr: "ƯCLN(30, 45) : 3 = ?",
    correctAnswer: 5,
    emojiAnalogy: "ƯCLN(30, 45) = 15 ➡️ 15 : 3 = 5 🖐️",
    explanation: "ƯCLN(30, 45) = 15, 15 : 3 = 5.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Thử thách",
  },
  {
    id: "g6_099",
    problemStr: "BCNN(3, 4) - 5 = ?",
    correctAnswer: 7,
    emojiAnalogy: "12 - 5 = 7 🎯",
    explanation: "BCNN(3, 4) = 12, 12 - 5 = 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "ƯCLN & BCNN",
    difficulty: "Trung bình",
  },
  {
    id: "g6_100",
    problemStr: "Số số nguyên tố nhỏ hơn 10 là?",
    correctAnswer: 4,
    emojiAnalogy: "{2, 3, 5, 7} = 4 số 🔢",
    explanation: "Có đúng 4 số nguyên tố nhỏ hơn 10: 2, 3, 5, 7.",
    gradeLevel: "Lớp 6 (THCS)",
    topic: "Số nguyên & Lũy thừa",
    difficulty: "Trung bình",
  },
];
