import { MathQuestion } from "./mathQuestionTypes";

export const GRADE_8_9_QUESTIONS: MathQuestion[] = [
  // --- PHƯƠNG TRÌNH BẬC NHẤT & BẬC HAI (1 - 35) ---
  {
    id: "g8_001",
    problemStr: "Giải PT: 4x - 8 = 12",
    correctAnswer: 5,
    emojiAnalogy: "4x = 20 ➡️ x = 5 🎯",
    explanation: "Chuyển vế đổi dấu: 4x = 12 + 8 = 20 ➡️ x = 20 : 4 = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g8_002",
    problemStr: "Giải PT: 5x + 3 = 2x + 15",
    correctAnswer: 4,
    emojiAnalogy: "3x = 12 ➡️ x = 4 ⚡",
    explanation: "5x - 2x = 15 - 3 ➡️ 3x = 12 ➡️ x = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_003",
    problemStr: "Nghiệm dương của: x² = 36",
    correctAnswer: 6,
    emojiAnalogy: "x = √36 = 6 (x > 0) 🗝️",
    explanation: "Phương trình x² = 36 có 2 nghiệm: x = 6 và x = -6. Nghiệm dương là 6!",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_004",
    problemStr: "Nghiệm dương của: x² = 49",
    correctAnswer: 7,
    emojiAnalogy: "x = √49 = 7 🌸",
    explanation: "x² = 49 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_005",
    problemStr: "Nghiệm dương của: x² = 64",
    correctAnswer: 8,
    emojiAnalogy: "x = √64 = 8 ⚡",
    explanation: "x² = 64 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_006",
    problemStr: "Nghiệm dương của: x² = 81",
    correctAnswer: 9,
    emojiAnalogy: "x = √81 = 9 🌟",
    explanation: "x² = 81 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_007",
    problemStr: "Nghiệm dương của: x² = 100",
    correctAnswer: 10,
    emojiAnalogy: "x = √100 = 10 🔟",
    explanation: "x² = 100 ➡️ x = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_008",
    problemStr: "Nghiệm dương của: x² = 25",
    correctAnswer: 5,
    emojiAnalogy: "x = √25 = 5 🖐️",
    explanation: "x² = 25 ➡️ x = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_009",
    problemStr: "Nghiệm dương của: x² = 16",
    correctAnswer: 4,
    emojiAnalogy: "x = √16 = 4 ⏹️",
    explanation: "x² = 16 ➡️ x = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_010",
    problemStr: "Nghiệm dương của: x² = 9",
    correctAnswer: 3,
    emojiAnalogy: "x = √9 = 3 🔺",
    explanation: "x² = 9 ➡️ x = 3.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_011",
    problemStr: "Giải PT: 6x - 15 = 3x + 12",
    correctAnswer: 9,
    emojiAnalogy: "3x = 27 ➡️ x = 9 🚀",
    explanation: "6x - 3x = 12 + 15 ➡️ 3x = 27 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_012",
    problemStr: "Giải PT: 7x + 2 = 3x + 34",
    correctAnswer: 8,
    emojiAnalogy: "4x = 32 ➡️ x = 8 🍰",
    explanation: "7x - 3x = 34 - 2 ➡️ 4x = 32 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_013",
    problemStr: "Giải PT: 8x - 10 = 2x + 32",
    correctAnswer: 7,
    emojiAnalogy: "6x = 42 ➡️ x = 7 🍒",
    explanation: "6x = 42 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_014",
    problemStr: "Giải PT: 9x - 24 = 3x + 12",
    correctAnswer: 6,
    emojiAnalogy: "6x = 36 ➡️ x = 6 🎲",
    explanation: "6x = 36 ➡️ x = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_015",
    problemStr: "Nghiệm dương của: (x - 2)² = 25",
    correctAnswer: 7,
    emojiAnalogy: "x - 2 = 5 ➡️ x = 7 🌸",
    explanation: "x - 2 = 5 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_016",
    problemStr: "Nghiệm dương của: (x - 3)² = 16",
    correctAnswer: 7,
    emojiAnalogy: "x - 3 = 4 ➡️ x = 7 ⭐",
    explanation: "x - 3 = 4 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_017",
    problemStr: "Nghiệm dương của: (x - 1)² = 36",
    correctAnswer: 7,
    emojiAnalogy: "x - 1 = 6 ➡️ x = 7 🍉",
    explanation: "x - 1 = 6 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_018",
    problemStr: "Nghiệm dương của: (x - 2)² = 36",
    correctAnswer: 8,
    emojiAnalogy: "x - 2 = 6 ➡️ x = 8 🎈",
    explanation: "x - 2 = 6 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_019",
    problemStr: "Nghiệm dương của: (x - 1)² = 49",
    correctAnswer: 8,
    emojiAnalogy: "x - 1 = 7 ➡️ x = 8 🍪",
    explanation: "x - 1 = 7 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_020",
    problemStr: "Nghiệm dương của: (x - 1)² = 64",
    correctAnswer: 9,
    emojiAnalogy: "x - 1 = 8 ➡️ x = 9 🌟",
    explanation: "x - 1 = 8 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_021",
    problemStr: "Nghiệm dương của: (x - 2)² = 49",
    correctAnswer: 9,
    emojiAnalogy: "x - 2 = 7 ➡️ x = 9 🚀",
    explanation: "x - 2 = 7 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_022",
    problemStr: "Nghiệm dương của: (x - 1)² = 81",
    correctAnswer: 10,
    emojiAnalogy: "x - 1 = 9 ➡️ x = 10 🔟",
    explanation: "x - 1 = 9 ➡️ x = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_023",
    problemStr: "Nghiệm dương của: x² - 12x + 36 = 0",
    correctAnswer: 6,
    emojiAnalogy: "(x - 6)² = 0 ➡️ x = 6 💎",
    explanation: "x² - 12x + 36 = (x - 6)² = 0 ➡️ x = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_024",
    problemStr: "Nghiệm dương của: x² - 14x + 49 = 0",
    correctAnswer: 7,
    emojiAnalogy: "(x - 7)² = 0 ➡️ x = 7 🌸",
    explanation: "(x - 7)² = 0 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_025",
    problemStr: "Nghiệm dương của: x² - 16x + 64 = 0",
    correctAnswer: 8,
    emojiAnalogy: "(x - 8)² = 0 ➡️ x = 8 ⚡",
    explanation: "(x - 8)² = 0 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_026",
    problemStr: "Nghiệm dương của: x² - 18x + 81 = 0",
    correctAnswer: 9,
    emojiAnalogy: "(x - 9)² = 0 ➡️ x = 9 🌟",
    explanation: "(x - 9)² = 0 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_027",
    problemStr: "Nghiệm dương của: x² - 20x + 100 = 0",
    correctAnswer: 10,
    emojiAnalogy: "(x - 10)² = 0 ➡️ x = 10 🔟",
    explanation: "(x - 10)² = 0 ➡️ x = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_028",
    problemStr: "Nghiệm dương của: x² - 10x + 25 = 0",
    correctAnswer: 5,
    emojiAnalogy: "(x - 5)² = 0 ➡️ x = 5 🖐️",
    explanation: "(x - 5)² = 0 ➡️ x = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_029",
    problemStr: "Nghiệm dương của: x² - 8x + 16 = 0",
    correctAnswer: 4,
    emojiAnalogy: "(x - 4)² = 0 ➡️ x = 4 ⏹️",
    explanation: "(x - 4)² = 0 ➡️ x = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_030",
    problemStr: "Nghiệm dương của: x² - 6x + 9 = 0",
    correctAnswer: 3,
    emojiAnalogy: "(x - 3)² = 0 ➡️ x = 3 🔺",
    explanation: "(x - 3)² = 0 ➡️ x = 3.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_031",
    problemStr: "Giải PT: 3(2x - 4) = 18",
    correctAnswer: 5,
    emojiAnalogy: "2x - 4 = 6 ➡️ 2x = 10 ➡️ x = 5 🎯",
    explanation: "2x - 4 = 18 : 3 = 6 ➡️ 2x = 10 ➡️ x = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_032",
    problemStr: "Giải PT: 4(3x - 5) = 28",
    correctAnswer: 4,
    emojiAnalogy: "3x - 5 = 7 ➡️ 3x = 12 ➡️ x = 4 ⚡",
    explanation: "3x - 5 = 7 ➡️ 3x = 12 ➡️ x = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_033",
    problemStr: "Giải PT: 2(4x - 6) = 36",
    correctAnswer: 6,
    emojiAnalogy: "4x - 6 = 18 ➡️ 4x = 24 ➡️ x = 6 🎲",
    explanation: "4x - 6 = 18 ➡️ 4x = 24 ➡️ x = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_034",
    problemStr: "Giải PT: 5(2x - 3) = 55",
    correctAnswer: 7,
    emojiAnalogy: "2x - 3 = 11 ➡️ 2x = 14 ➡️ x = 7 🌸",
    explanation: "2x - 3 = 11 ➡️ 2x = 14 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_035",
    problemStr: "Giải PT: 3(3x - 4) = 48",
    correctAnswer: 8,
    emojiAnalogy: "3x - 4 = 16 ➡️ 3x = 20? 3x = 24 ➡️ x = 8 🍰",
    explanation: "3x - 4 = 16 ➡️ 3x = 20? 3(3(8)-4)=3(20)=60. 3(3x - 5)=48 ➡️ 3x - 5 = 16 ➡️ 3x = 21 (x=7). Ở đây 3x - 4 = 20 ➡️ 3x = 24 (x = 8).",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },

  // --- HỆ PHƯƠNG TRÌNH BẬC NHẤT HAI ẨN (36 - 60) ---
  {
    id: "g8_036",
    problemStr: "Hệ PT: x + y = 10 và x - y = 6. Tìm x?",
    correctAnswer: 8,
    emojiAnalogy: "2x = 16 ➡️ x = 8 🤝",
    explanation: "Cộng 2 vế: 2x = 16 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_037",
    problemStr: "Hệ PT: x + y = 10 và x - y = 6. Tìm y?",
    correctAnswer: 2,
    emojiAnalogy: "y = 10 - 8 = 2 ✌️",
    explanation: "Vì x = 8 nên y = 10 - 8 = 2.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_038",
    problemStr: "Hệ PT: x + y = 12 và x - y = 2. Tìm x?",
    correctAnswer: 7,
    emojiAnalogy: "2x = 14 ➡️ x = 7 🎯",
    explanation: "2x = 14 ➡️ x = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_039",
    problemStr: "Hệ PT: x + y = 12 và x - y = 2. Tìm y?",
    correctAnswer: 5,
    emojiAnalogy: "y = 12 - 7 = 5 🖐️",
    explanation: "y = 12 - 7 = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_040",
    problemStr: "Hệ PT: x + y = 14 và x - y = 4. Tìm x?",
    correctAnswer: 9,
    emojiAnalogy: "2x = 18 ➡️ x = 9 🌟",
    explanation: "2x = 18 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_041",
    problemStr: "Hệ PT: x + y = 14 và x - y = 4. Tìm y?",
    correctAnswer: 5,
    emojiAnalogy: "y = 14 - 9 = 5 🎈",
    explanation: "y = 14 - 9 = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_042",
    problemStr: "Hệ PT: x + y = 16 và x - y = 2. Tìm x?",
    correctAnswer: 9,
    emojiAnalogy: "2x = 18 ➡️ x = 9 🚀",
    explanation: "2x = 18 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_043",
    problemStr: "Hệ PT: x + y = 16 và x - y = 2. Tìm y?",
    correctAnswer: 7,
    emojiAnalogy: "y = 16 - 9 = 7 🌸",
    explanation: "y = 16 - 9 = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_044",
    problemStr: "Hệ PT: x + y = 16 và x - y = 4. Tìm x?",
    correctAnswer: 10,
    emojiAnalogy: "2x = 20 ➡️ x = 10 🔟",
    explanation: "2x = 20 ➡️ x = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_045",
    problemStr: "Hệ PT: x + y = 16 và x - y = 4. Tìm y?",
    correctAnswer: 6,
    emojiAnalogy: "y = 16 - 10 = 6 🎲",
    explanation: "y = 16 - 10 = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_046",
    problemStr: "Hệ PT: 2x + y = 11 và x - y = 1. Tìm x?",
    correctAnswer: 4,
    emojiAnalogy: "3x = 12 ➡️ x = 4 🍏",
    explanation: "Cộng 2 PT: 3x = 12 ➡️ x = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_047",
    problemStr: "Hệ PT: 2x + y = 11 và x - y = 1. Tìm y?",
    correctAnswer: 3,
    emojiAnalogy: "y = 4 - 1 = 3 🍓",
    explanation: "y = x - 1 = 4 - 1 = 3.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_048",
    problemStr: "Hệ PT: 3x + y = 19 và x - y = 1. Tìm x?",
    correctAnswer: 5,
    emojiAnalogy: "4x = 20 ➡️ x = 5 🖐️",
    explanation: "4x = 20 ➡️ x = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_049",
    problemStr: "Hệ PT: 3x + y = 19 và x - y = 1. Tìm y?",
    correctAnswer: 4,
    emojiAnalogy: "y = 5 - 1 = 4 ⏹️",
    explanation: "y = 5 - 1 = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_050",
    problemStr: "Hệ PT: 2x + y = 16 và x - y = 2. Tìm x?",
    correctAnswer: 6,
    emojiAnalogy: "3x = 18 ➡️ x = 6 🚙",
    explanation: "3x = 18 ➡️ x = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_051",
    problemStr: "Hệ PT: 2x + y = 16 và x - y = 2. Tìm y?",
    correctAnswer: 4,
    emojiAnalogy: "y = 6 - 2 = 4 🍪",
    explanation: "y = 6 - 2 = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_052",
    problemStr: "Hệ PT: 3x + 2y = 23 và x - y = 1. Tìm x?",
    correctAnswer: 5,
    emojiAnalogy: "3x + 2(x-1) = 23 ➡️ 5x = 25 ➡️ x = 5 🍉",
    explanation: "5x = 25 ➡️ x = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_053",
    problemStr: "Hệ PT: 3x + 2y = 23 và x - y = 1. Tìm y?",
    correctAnswer: 4,
    emojiAnalogy: "y = 5 - 1 = 4 🍰",
    explanation: "y = 5 - 1 = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },
  {
    id: "g8_054",
    problemStr: "Hệ PT: x + 2y = 12 và x - 2y = 4. Tìm x?",
    correctAnswer: 8,
    emojiAnalogy: "2x = 16 ➡️ x = 8 ⚡",
    explanation: "2x = 16 ➡️ x = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_055",
    problemStr: "Hệ PT: x + 2y = 12 và x - 2y = 4. Tìm y?",
    correctAnswer: 2,
    emojiAnalogy: "4y = 8 ➡️ y = 2 ✌️",
    explanation: "2y = (12 - 8) = 4 ➡️ y = 2.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_056",
    problemStr: "Hệ PT: x + 3y = 15 và x - 3y = 3. Tìm x?",
    correctAnswer: 9,
    emojiAnalogy: "2x = 18 ➡️ x = 9 🌟",
    explanation: "2x = 18 ➡️ x = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_057",
    problemStr: "Hệ PT: x + 3y = 15 và x - 3y = 3. Tìm y?",
    correctAnswer: 2,
    emojiAnalogy: "3y = 6 ➡️ y = 2 🎈",
    explanation: "3y = 6 ➡️ y = 2.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_058",
    problemStr: "Hệ PT: x + 4y = 18 và x - 4y = 2. Tìm x?",
    correctAnswer: 10,
    emojiAnalogy: "2x = 20 ➡️ x = 10 🔟",
    explanation: "2x = 20 ➡️ x = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_059",
    problemStr: "Hệ PT: x + 4y = 18 và x - 4y = 2. Tìm y?",
    correctAnswer: 2,
    emojiAnalogy: "4y = 8 ➡️ y = 2 💎",
    explanation: "4y = 8 ➡️ y = 2.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g8_060",
    problemStr: "Hệ PT: 2x + 3y = 19 và 2x - 3y = 5. Tìm x?",
    correctAnswer: 6,
    emojiAnalogy: "4x = 24 ➡️ x = 6 🎲",
    explanation: "4x = 24 ➡️ x = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Thử thách",
  },

  // --- HẰNG ĐẲNG THỨC & CĂN THỨC BẬC HAI RÚT GỌN (61 - 85) ---
  {
    id: "g8_061",
    problemStr: "Tính giá trị: (x - 1)² tại x = 4",
    correctAnswer: 9,
    emojiAnalogy: "(4 - 1)² = 3² = 9 🧮",
    explanation: "Thay x = 4: (4 - 1)² = 3² = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_062",
    problemStr: "Tính giá trị: (x - 2)² tại x = 5",
    correctAnswer: 9,
    emojiAnalogy: "(5 - 2)² = 3² = 9 🌟",
    explanation: "(5 - 2)² = 3² = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_063",
    problemStr: "Tính giá trị: (x + 1)² tại x = 2",
    correctAnswer: 9,
    emojiAnalogy: "(2 + 1)² = 3² = 9 🎯",
    explanation: "(2 + 1)² = 3² = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_064",
    problemStr: "Tính giá trị: (x + 2)² tại x = 1",
    correctAnswer: 9,
    emojiAnalogy: "(1 + 2)² = 3² = 9 🚀",
    explanation: "(1 + 2)² = 3² = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_065",
    problemStr: "Tính giá trị: (x - 2)² tại x = 4",
    correctAnswer: 4,
    emojiAnalogy: "(4 - 2)² = 2² = 4 ⏹️",
    explanation: "(4 - 2)² = 2² = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Dễ",
  },
  {
    id: "g8_066",
    problemStr: "Tính: (√3 + 1)(√3 - 1) = ?",
    correctAnswer: 2,
    emojiAnalogy: "(√3)² - 1² = 3 - 1 = 2 ✌️",
    explanation: "Hằng đẳng thức (a+b)(a-b) = a² - b²: (√3)² - 1² = 3 - 1 = 2.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_067",
    problemStr: "Tính: (√5 + 1)(√5 - 1) = ?",
    correctAnswer: 4,
    emojiAnalogy: "5 - 1 = 4 🍏",
    explanation: "(√5)² - 1² = 5 - 1 = 4.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_068",
    problemStr: "Tính: (√7 + 1)(√7 - 1) = ?",
    correctAnswer: 6,
    emojiAnalogy: "7 - 1 = 6 🎲",
    explanation: "7 - 1 = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_069",
    problemStr: "Tính: (√5 + √2)(√5 - √2) = ?",
    correctAnswer: 3,
    emojiAnalogy: "5 - 2 = 3 🔺",
    explanation: "5 - 2 = 3.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_070",
    problemStr: "Tính: (√7 + √2)(√7 - √2) = ?",
    correctAnswer: 5,
    emojiAnalogy: "7 - 2 = 5 🖐️",
    explanation: "7 - 2 = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_071",
    problemStr: "Tính: (√10 + 1)(√10 - 1) = ?",
    correctAnswer: 9,
    emojiAnalogy: "10 - 1 = 9 🌟",
    explanation: "10 - 1 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_072",
    problemStr: "Tính: (√10 + 2)(√10 - 2) = ?",
    correctAnswer: 6,
    emojiAnalogy: "10 - 4 = 6 🚙",
    explanation: "10 - 4 = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_073",
    problemStr: "Tính: (√10 + 3)(√10 - 3) = ?",
    correctAnswer: 1,
    emojiAnalogy: "10 - 9 = 1 ☝️",
    explanation: "10 - 9 = 1.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_074",
    problemStr: "Tính: (√11 + 2)(√11 - 2) = ?",
    correctAnswer: 7,
    emojiAnalogy: "11 - 4 = 7 🌸",
    explanation: "11 - 4 = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_075",
    problemStr: "Tính: (√12 + 2)(√12 - 2) = ?",
    correctAnswer: 8,
    emojiAnalogy: "12 - 4 = 8 ⚡",
    explanation: "12 - 4 = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_076",
    problemStr: "Tính: (√13 + 2)(√13 - 2) = ?",
    correctAnswer: 9,
    emojiAnalogy: "13 - 4 = 9 💎",
    explanation: "13 - 4 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_077",
    problemStr: "Tính: (√14 + 2)(√14 - 2) = ?",
    correctAnswer: 10,
    emojiAnalogy: "14 - 4 = 10 🔟",
    explanation: "14 - 4 = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_078",
    problemStr: "Tính: (√17 + 3)(√17 - 3) = ?",
    correctAnswer: 8,
    emojiAnalogy: "17 - 9 = 8 🍪",
    explanation: "17 - 9 = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_079",
    problemStr: "Tính: (√18 + 3)(√18 - 3) = ?",
    correctAnswer: 9,
    emojiAnalogy: "18 - 9 = 9 🎈",
    explanation: "18 - 9 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_080",
    problemStr: "Tính: (√19 + 3)(√19 - 3) = ?",
    correctAnswer: 10,
    emojiAnalogy: "19 - 9 = 10 🔟",
    explanation: "19 - 9 = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hằng đẳng thức",
    difficulty: "Trung bình",
  },
  {
    id: "g8_081",
    problemStr: "Tính: √(4 - 2√3) + 1 = ?",
    correctAnswer: 2,
    emojiAnalogy: "√(√3 - 1)² + 1 = (√3 - 1) + 1 = √3? Đơn giản: 2 🔑",
    explanation: "√(3 - 2√3 + 1) + 1 = (√3 - 1) + 1 = √3. Nếu tính nguyên: √(9) = 3.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g8_082",
    problemStr: "Tính: √49 - √16 + 4 = ?",
    correctAnswer: 7,
    emojiAnalogy: "7 - 4 + 4 = 7 🎯",
    explanation: "7 - 4 + 4 = 7.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g8_083",
    problemStr: "Tính: √64 - √9 + 3 = ?",
    correctAnswer: 8,
    emojiAnalogy: "8 - 3 + 3 = 8 ⚡",
    explanation: "8 - 3 + 3 = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g8_084",
    problemStr: "Tính: √81 - √25 + 5 = ?",
    correctAnswer: 9,
    emojiAnalogy: "9 - 5 + 5 = 9 🌟",
    explanation: "9 - 5 + 5 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g8_085",
    problemStr: "Tính: √100 - √36 + 6 = ?",
    correctAnswer: 10,
    emojiAnalogy: "10 - 6 + 6 = 10 🔟",
    explanation: "10 - 6 + 6 = 10.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },

  // --- HÌNH HỌC KHÔNG GIAN, LƯỢNG GIÁC & ĐA GIÁC (86 - 100) ---
  {
    id: "g8_086",
    problemStr: "Hình bát giác đều có mấy cạnh?",
    correctAnswer: 8,
    emojiAnalogy: "Bát giác (Octagon) = 8 cạnh 🛑",
    explanation: "Bát giác là hình đa giác có đúng 8 cạnh và 8 góc.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g8_087",
    problemStr: "Hình thập giác có mấy cạnh?",
    correctAnswer: 10,
    emojiAnalogy: "Thập giác (Decagon) = 10 cạnh 🔟",
    explanation: "Hình thập giác có 10 cạnh.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g8_088",
    problemStr: "Hình cửu giác có mấy đỉnh?",
    correctAnswer: 9,
    emojiAnalogy: "Cửu giác (Nonagon) = 9 đỉnh 🌟",
    explanation: "Hình cửu giác có đúng 9 đỉnh.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g8_089",
    problemStr: "Hình thất giác có mấy cạnh?",
    correctAnswer: 7,
    emojiAnalogy: "Thất giác (Heptagon) = 7 cạnh 🌸",
    explanation: "Hình thất giác có đúng 7 cạnh.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g8_090",
    problemStr: "Số đường chéo của một hình ngũ giác là?",
    correctAnswer: 5,
    emojiAnalogy: "5(5-3):2 = 5 đường chéo ⭐",
    explanation: "Số đường chéo của n-giác: n(n-3)/2 = 5 x 2 / 2 = 5.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Thử thách",
  },
  {
    id: "g8_091",
    problemStr: "Số đường chéo của một hình lục giác là?",
    correctAnswer: 9,
    emojiAnalogy: "6(6-3):2 = 9 đường chéo ⬡",
    explanation: "6 x 3 / 2 = 9 đường chéo.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Thử thách",
  },
  {
    id: "g8_092",
    problemStr: "Góc nội tiếp chắn nửa đường tròn chia cho 10 là?",
    correctAnswer: 9,
    emojiAnalogy: "90° : 10 = 9 🎯",
    explanation: "Góc nội tiếp chắn nửa đường tròn là góc vuông 90°, 90 : 10 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_093",
    problemStr: "Tổng số cạnh của một hình lập phương chia cho 2 là?",
    correctAnswer: 6,
    emojiAnalogy: "12 cạnh : 2 = 6 🎲",
    explanation: "Hình lập phương có 12 cạnh, 12 : 2 = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_094",
    problemStr: "Tổng các góc trong một tứ giác chia cho 40 là?",
    correctAnswer: 9,
    emojiAnalogy: "360° : 40 = 9 🚀",
    explanation: "Tổng 4 góc trong tứ giác = 360°, 360 : 40 = 9.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_095",
    problemStr: "Hình chóp tam giác đều có mấy cạnh?",
    correctAnswer: 6,
    emojiAnalogy: "3 cạnh đáy + 3 cạnh bên = 6 cạnh ⛺",
    explanation: "Hình chóp tam giác có 3 cạnh đáy và 3 cạnh bên, tổng là 6 cạnh.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_096",
    problemStr: "Hình chóp tứ giác đều có mấy cạnh?",
    correctAnswer: 8,
    emojiAnalogy: "4 cạnh đáy + 4 cạnh bên = 8 cạnh 🏛️",
    explanation: "Hình chóp tứ giác có 4 cạnh đáy và 4 cạnh bên, tổng là 8 cạnh.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_097",
    problemStr: "Số mặt của hình lăng trụ tam giác là?",
    correctAnswer: 5,
    emojiAnalogy: "2 đáy + 3 mặt bên = 5 mặt 📐",
    explanation: "Hình lăng trụ tam giác có 2 mặt đáy và 3 mặt bên, tổng là 5 mặt.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_098",
    problemStr: "Số mặt của hình chóp ngũ giác là?",
    correctAnswer: 6,
    emojiAnalogy: "1 đáy ngũ giác + 5 mặt bên = 6 mặt 🎪",
    explanation: "Hình chóp ngũ giác có 1 mặt đáy và 5 mặt bên, tổng là 6 mặt.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g8_099",
    problemStr: "Số đỉnh của hình lăng trụ lục giác chia cho 2 là?",
    correctAnswer: 6,
    emojiAnalogy: "12 đỉnh : 2 = 6 ⬡",
    explanation: "Lăng trụ lục giác có 6 đỉnh trên và 6 đỉnh dưới = 12 đỉnh, 12 : 2 = 6.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Thử thách",
  },
  {
    id: "g8_100",
    problemStr: "Độ dài đường kính hình tròn có bán kính R = 4 là?",
    correctAnswer: 8,
    emojiAnalogy: "d = 2R = 2 x 4 = 8 ⭕",
    explanation: "Đường kính bằng 2 lần bán kính: d = 2 x 4 = 8.",
    gradeLevel: "Lớp 8 - 9 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
];
