import { MathQuestion } from "./mathQuestionTypes";

export const GRADE_1_2_QUESTIONS: MathQuestion[] = [
  // --- CỘNG CƠ BẢN TRONG PHẠM VI 10 (1 - 25) ---
  {
    id: "g1_001",
    problemStr: "2 + 3 = ?",
    correctAnswer: 5,
    emojiAnalogy: "🍎🍎 + 🍎🍎🍎 = 5 🍎",
    explanation: "2 quả táo thêm 3 quả táo là 5 quả táo!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_002",
    problemStr: "4 + 3 = ?",
    correctAnswer: 7,
    emojiAnalogy: "⭐⭐⭐⭐ + ⭐⭐⭐ = 7 ⭐",
    explanation: "4 ngôi sao cộng 3 ngôi sao bằng 7 ngôi sao.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_003",
    problemStr: "5 + 5 = ?",
    correctAnswer: 10,
    emojiAnalogy: "✋ (5) + ✋ (5) = 🔟 ngón",
    explanation: "5 ngón tay cộng 5 ngón tay là trọn vẹn 10 ngón tay!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_004",
    problemStr: "1 + 7 = ?",
    correctAnswer: 8,
    emojiAnalogy: "🍓 + 🍓🍓🍓🍓🍓🍓🍓 = 8 🍓",
    explanation: "1 thêm 7 bằng 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_005",
    problemStr: "6 + 3 = ?",
    correctAnswer: 9,
    emojiAnalogy: "🎈🎈🎈🎈🎈🎈 + 🎈🎈🎈 = 9 🎈",
    explanation: "6 quả bóng cộng 3 quả bóng bằng 9 quả bóng!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_006",
    problemStr: "2 + 6 = ?",
    correctAnswer: 8,
    emojiAnalogy: "🚗🚗 + 🚗🚗🚗🚗🚗🚗 = 8 🚗",
    explanation: "2 xe cộng 6 xe là 8 chiếc xe.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_007",
    problemStr: "0 + 6 = ?",
    correctAnswer: 6,
    emojiAnalogy: "0 + 🐱🐱🐱🐱🐱🐱 = 6 🐱",
    explanation: "Bất kỳ số nào cộng với 0 cũng bằng chính nó.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_008",
    problemStr: "4 + 5 = ?",
    correctAnswer: 9,
    emojiAnalogy: "🌸🌸🌸🌸 + 🌸🌸🌸🌸🌸 = 9 🌸",
    explanation: "4 bông hoa thêm 5 bông hoa bằng 9 bông hoa.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_009",
    problemStr: "3 + 3 = ?",
    correctAnswer: 6,
    emojiAnalogy: "🍪🍪🍪 + 🍪🍪🍪 = 6 🍪",
    explanation: "3 chiếc bánh cộng 3 chiếc bánh là 6 chiếc bánh!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_010",
    problemStr: "1 + 9 = ?",
    correctAnswer: 10,
    emojiAnalogy: "1 + 9 = 10 🎯",
    explanation: "1 thêm 9 bằng 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_011",
    problemStr: "4 + 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "🐥🐥🐥🐥 + 🐥🐥🐥🐥 = 8 🐥",
    explanation: "4 chú gà con thêm 4 chú gà con bằng 8 chú gà con.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_012",
    problemStr: "2 + 2 = ?",
    correctAnswer: 4,
    emojiAnalogy: "🐰🐰 + 🐰🐰 = 4 🐰",
    explanation: "2 con thỏ thêm 2 con thỏ bằng 4 con thỏ!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_013",
    problemStr: "3 + 1 = ?",
    correctAnswer: 4,
    emojiAnalogy: "⚽⚽⚽ + ⚽ = 4 ⚽",
    explanation: "3 quả bóng thêm 1 quả bóng bằng 4 quả bóng.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_014",
    problemStr: "2 + 7 = ?",
    correctAnswer: 9,
    emojiAnalogy: "🌻🌻 + 7 🌻 = 9 🌻",
    explanation: "2 cộng 7 bằng 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_015",
    problemStr: "1 + 4 = ?",
    correctAnswer: 5,
    emojiAnalogy: "🍬 + 🍬🍬🍬🍬 = 5 🍬",
    explanation: "1 viên kẹo thêm 4 viên kẹo bằng 5 viên kẹo.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_016",
    problemStr: "3 + 4 = ?",
    correctAnswer: 7,
    emojiAnalogy: "🍊🍊🍊 + 🍊🍊🍊🍊 = 7 🍊",
    explanation: "3 quả cam thêm 4 quả cam bằng 7 quả cam.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_017",
    problemStr: "5 + 1 = ?",
    correctAnswer: 6,
    emojiAnalogy: "5 ✏️ + 1 ✏️ = 6 ✏️",
    explanation: "5 chiếc bút chì thêm 1 chiếc bằng 6 chiếc.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_018",
    problemStr: "4 + 2 = ?",
    correctAnswer: 6,
    emojiAnalogy: "4 🍦 + 2 🍦 = 6 🍦",
    explanation: "4 cây kem thêm 2 cây kem là 6 cây kem.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_019",
    problemStr: "7 + 3 = ?",
    correctAnswer: 10,
    emojiAnalogy: "7 + 3 = 10 🔟",
    explanation: "7 cộng 3 bằng 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_020",
    problemStr: "8 + 2 = ?",
    correctAnswer: 10,
    emojiAnalogy: "8 + 2 = 10 🌟",
    explanation: "8 thêm 2 được 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_021",
    problemStr: "3 + 5 = ?",
    correctAnswer: 8,
    emojiAnalogy: "3 🍉 + 5 🍉 = 8 🍉",
    explanation: "3 miếng dưa hấu cộng 5 miếng là 8 miếng!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_022",
    problemStr: "6 + 1 = ?",
    correctAnswer: 7,
    emojiAnalogy: "6 🍩 + 1 🍩 = 7 🍩",
    explanation: "6 chiếc bánh thêm 1 chiếc bằng 7 chiếc.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_023",
    problemStr: "1 + 1 = ?",
    correctAnswer: 2,
    emojiAnalogy: "🦆 + 🦆 = 2 🦆",
    explanation: "1 con vịt thêm 1 con vịt là 2 con vịt.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_024",
    problemStr: "2 + 1 = ?",
    correctAnswer: 3,
    emojiAnalogy: "2 🐟 + 1 🐟 = 3 🐟",
    explanation: "2 con cá thêm 1 con cá là 3 con cá.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_025",
    problemStr: "6 + 4 = ?",
    correctAnswer: 10,
    emojiAnalogy: "6 + 4 = 10 🌈",
    explanation: "6 cộng 4 bằng 10!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },

  // --- TRỪ CƠ BẢN TRONG PHẠM VI 10 (26 - 50) ---
  {
    id: "g1_026",
    problemStr: "8 - 2 = ?",
    correctAnswer: 6,
    emojiAnalogy: "🎈🎈🎈🎈🎈🎈🎈🎈 bớt đi 2 = 6 🎈",
    explanation: "8 quả bóng bớt 2 quả bóng còn 6 quả.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_027",
    problemStr: "9 - 4 = ?",
    correctAnswer: 5,
    emojiAnalogy: "9 ⭐ - 4 ⭐ = 5 ⭐",
    explanation: "9 trừ đi 4 bằng 5.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_028",
    problemStr: "10 - 3 = ?",
    correctAnswer: 7,
    emojiAnalogy: "10 🍎 bớt đi 3 🍎 = 7 🍎",
    explanation: "10 trừ đi 3 bằng 7!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_029",
    problemStr: "7 - 5 = ?",
    correctAnswer: 2,
    emojiAnalogy: "7 🍭 - 5 🍭 = 2 🍭",
    explanation: "7 chiếc kẹo mút ăn mất 5 chiếc còn 2 chiếc.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_030",
    problemStr: "10 - 6 = ?",
    correctAnswer: 4,
    emojiAnalogy: "10 - 6 = 4 🎯",
    explanation: "10 bớt đi 6 còn lại 4.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_031",
    problemStr: "6 - 3 = ?",
    correctAnswer: 3,
    emojiAnalogy: "6 🍓 - 3 🍓 = 3 🍓",
    explanation: "6 quả dâu bớt 3 quả còn 3 quả.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_032",
    problemStr: "5 - 4 = ?",
    correctAnswer: 1,
    emojiAnalogy: "5 🍌 - 4 🍌 = 1 🍌",
    explanation: "5 trừ 4 bằng 1.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_033",
    problemStr: "8 - 8 = ?",
    correctAnswer: 0,
    emojiAnalogy: "8 🍪 - 8 🍪 = 0 🍪 (Nắm tay ✊)",
    explanation: "8 chiếc bánh ăn hết 8 chiếc còn lại 0 chiếc! (Giơ nắm đấm ✊)",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_034",
    problemStr: "10 - 1 = ?",
    correctAnswer: 9,
    emojiAnalogy: "10 - 1 = 9 🌟",
    explanation: "10 bớt 1 còn 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_035",
    problemStr: "9 - 2 = ?",
    correctAnswer: 7,
    emojiAnalogy: "9 🚗 - 2 🚗 = 7 🚗",
    explanation: "9 chiếc xe rời đi 2 chiếc còn 7 chiếc.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_036",
    problemStr: "7 - 4 = ?",
    correctAnswer: 3,
    emojiAnalogy: "7 🌸 - 4 🌸 = 3 🌸",
    explanation: "7 trừ 4 bằng 3.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_037",
    problemStr: "10 - 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "10 - 2 = 8 🎈",
    explanation: "10 trừ đi 2 bằng 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_038",
    problemStr: "6 - 2 = ?",
    correctAnswer: 4,
    emojiAnalogy: "6 🐥 - 2 🐥 = 4 🐥",
    explanation: "6 con vịt bớt 2 con còn 4 con.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_039",
    problemStr: "5 - 2 = ?",
    correctAnswer: 3,
    emojiAnalogy: "5 🍊 - 2 🍊 = 3 🍊",
    explanation: "5 quả cam trừ 2 quả bằng 3 quả.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_040",
    problemStr: "10 - 5 = ?",
    correctAnswer: 5,
    emojiAnalogy: "🔟 - ✋ = 5 ✋",
    explanation: "10 ngón tay cụp 1 bàn tay 5 ngón còn 5 ngón.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_041",
    problemStr: "8 - 5 = ?",
    correctAnswer: 3,
    emojiAnalogy: "8 - 5 = 3 🍎",
    explanation: "8 bớt 5 bằng 3.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_042",
    problemStr: "9 - 6 = ?",
    correctAnswer: 3,
    emojiAnalogy: "9 - 6 = 3 🍦",
    explanation: "9 trừ 6 bằng 3.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_043",
    problemStr: "4 - 3 = ?",
    correctAnswer: 1,
    emojiAnalogy: "4 🍉 - 3 🍉 = 1 🍉",
    explanation: "4 trừ 3 bằng 1.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_044",
    problemStr: "7 - 1 = ?",
    correctAnswer: 6,
    emojiAnalogy: "7 🎈 - 1 🎈 = 6 🎈",
    explanation: "7 bớt 1 bằng 6.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_045",
    problemStr: "10 - 8 = ?",
    correctAnswer: 2,
    emojiAnalogy: "10 - 8 = 2 ✌️",
    explanation: "10 trừ 8 bằng 2.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_046",
    problemStr: "9 - 7 = ?",
    correctAnswer: 2,
    emojiAnalogy: "9 - 7 = 2 🍓",
    explanation: "9 bớt đi 7 còn 2.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_047",
    problemStr: "8 - 1 = ?",
    correctAnswer: 7,
    emojiAnalogy: "8 - 1 = 7 ⭐",
    explanation: "8 trừ 1 bằng 7.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_048",
    problemStr: "10 - 0 = ?",
    correctAnswer: 10,
    emojiAnalogy: "10 - 0 = 10 🔟",
    explanation: "Một số trừ đi 0 vẫn bằng chính nó!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_049",
    problemStr: "6 - 5 = ?",
    correctAnswer: 1,
    emojiAnalogy: "6 - 5 = 1 🍬",
    explanation: "6 trừ 5 bằng 1.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_050",
    problemStr: "5 - 5 = ?",
    correctAnswer: 0,
    emojiAnalogy: "5 - 5 = 0 ✊",
    explanation: "5 trừ đi chính nó bằng 0 (Nắm tay lại ✊)!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },

  // --- BIỂU THỨC 3 SỐ VÀ TÌM Ô TRỐNG (51 - 75) ---
  {
    id: "g1_051",
    problemStr: "2 + 3 + 4 = ?",
    correctAnswer: 9,
    emojiAnalogy: "(2 + 3) + 4 = 5 + 4 = 9 🌟",
    explanation: "2 cộng 3 bằng 5, lấy 5 cộng tiếp 4 bằng 9!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_052",
    problemStr: "10 - 4 - 3 = ?",
    correctAnswer: 3,
    emojiAnalogy: "10 - 4 = 6; 6 - 3 = 3 🎈",
    explanation: "10 trừ 4 còn 6, 6 trừ tiếp 3 còn 3.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_053",
    problemStr: "3 + 4 - 2 = ?",
    correctAnswer: 5,
    emojiAnalogy: "3 + 4 = 7; 7 - 2 = 5 🍎",
    explanation: "3 cộng 4 là 7, 7 bớt 2 còn 5.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_054",
    problemStr: "8 - 5 + 4 = ?",
    correctAnswer: 7,
    emojiAnalogy: "8 - 5 = 3; 3 + 4 = 7 🌸",
    explanation: "8 trừ 5 bằng 3, 3 cộng 4 bằng 7.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_055",
    problemStr: "Tìm số: 4 + ? = 9",
    correctAnswer: 5,
    emojiAnalogy: "9 - 4 = 5 💡",
    explanation: "Muốn tìm số hạng chưa biết, lấy tổng trừ số hạng kia: 9 - 4 = 5.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_056",
    problemStr: "Tìm số: ? + 3 = 8",
    correctAnswer: 5,
    emojiAnalogy: "8 - 3 = 5 🔑",
    explanation: "8 trừ 3 bằng 5, vậy số cần điền là 5.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_057",
    problemStr: "Tìm số: 10 - ? = 4",
    correctAnswer: 6,
    emojiAnalogy: "10 - 4 = 6 🚪",
    explanation: "Số trừ = Số bị trừ - Hiệu: 10 - 4 = 6.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_058",
    problemStr: "Tìm số: ? - 2 = 7",
    correctAnswer: 9,
    emojiAnalogy: "7 + 2 = 9 🚀",
    explanation: "Số bị trừ = Hiệu + Số trừ: 7 + 2 = 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_059",
    problemStr: "1 + 2 + 3 = ?",
    correctAnswer: 6,
    emojiAnalogy: "1 + 2 + 3 = 6 🎲",
    explanation: "1 cộng 2 là 3, thêm 3 nữa là 6!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_060",
    problemStr: "2 + 2 + 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 + 4 = 8 🍪",
    explanation: "2 cộng 2 là 4, 4 cộng 4 bằng 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_061",
    problemStr: "1 + 4 + 5 = ?",
    correctAnswer: 10,
    emojiAnalogy: "5 + 5 = 10 🔟",
    explanation: "1 + 4 = 5, 5 + 5 = 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_062",
    problemStr: "9 - 3 - 2 = ?",
    correctAnswer: 4,
    emojiAnalogy: "6 - 2 = 4 🍬",
    explanation: "9 - 3 = 6; 6 - 2 = 4.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_063",
    problemStr: "7 - 3 + 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 + 4 = 8 🐥",
    explanation: "7 - 3 = 4, 4 + 4 = 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_064",
    problemStr: "10 - 7 + 3 = ?",
    correctAnswer: 6,
    emojiAnalogy: "3 + 3 = 6 🌟",
    explanation: "10 - 7 = 3, 3 + 3 = 6.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_065",
    problemStr: "Tìm số: 5 + ? = 8",
    correctAnswer: 3,
    emojiAnalogy: "8 - 5 = 3 🍓",
    explanation: "5 cộng 3 bằng 8!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g1_066",
    problemStr: "Tìm số: 6 + ? = 10",
    correctAnswer: 4,
    emojiAnalogy: "10 - 6 = 4 🎯",
    explanation: "6 cộng 4 bằng 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g1_067",
    problemStr: "Tìm số: ? + 7 = 9",
    correctAnswer: 2,
    emojiAnalogy: "9 - 7 = 2 ✌️",
    explanation: "2 cộng 7 bằng 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g1_068",
    problemStr: "Tìm số: ? - 3 = 5",
    correctAnswer: 8,
    emojiAnalogy: "5 + 3 = 8 🎈",
    explanation: "8 trừ 3 bằng 5.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_069",
    problemStr: "Tìm số: 9 - ? = 2",
    correctAnswer: 7,
    emojiAnalogy: "9 - 2 = 7 ⭐",
    explanation: "9 trừ 7 bằng 2.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g1_070",
    problemStr: "2 + 5 - 3 = ?",
    correctAnswer: 4,
    emojiAnalogy: "7 - 3 = 4 🍀",
    explanation: "2 + 5 = 7, 7 - 3 = 4.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_071",
    problemStr: "10 - 1 - 8 = ?",
    correctAnswer: 1,
    emojiAnalogy: "9 - 8 = 1 ☝️",
    explanation: "10 - 1 = 9, 9 - 8 = 1.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_072",
    problemStr: "3 + 3 + 3 = ?",
    correctAnswer: 9,
    emojiAnalogy: "3 + 3 + 3 = 9 🚀",
    explanation: "3 lần số 3 bằng 9!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_073",
    problemStr: "2 + 3 + 2 = ?",
    correctAnswer: 7,
    emojiAnalogy: "5 + 2 = 7 🌸",
    explanation: "2 + 3 = 5, 5 + 2 = 7.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_074",
    problemStr: "8 - 4 - 2 = ?",
    correctAnswer: 2,
    emojiAnalogy: "4 - 2 = 2 🐟",
    explanation: "8 - 4 = 4, 4 - 2 = 2.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Trung bình",
  },
  {
    id: "g1_075",
    problemStr: "1 + 6 + 1 = ?",
    correctAnswer: 8,
    emojiAnalogy: "7 + 1 = 8 🍰",
    explanation: "1 + 6 = 7, 7 + 1 = 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },

  // --- PHÉP NHÂN CƠ BẢN & TOÁN ĐỐ HÌNH HỌC (76 - 100) ---
  {
    id: "g1_076",
    problemStr: "2 x 3 = ?",
    correctAnswer: 6,
    emojiAnalogy: "2 nhóm x 3 quả = 6 🍎",
    explanation: "2 nhân 3 bằng 6 (3 + 3 = 6).",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_077",
    problemStr: "2 x 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 + 4 = 8 🍪",
    explanation: "2 nhân 4 bằng 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_078",
    problemStr: "2 x 5 = ?",
    correctAnswer: 10,
    emojiAnalogy: "5 + 5 = 10 🔟",
    explanation: "2 nhân 5 bằng 10.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_079",
    problemStr: "3 x 3 = ?",
    correctAnswer: 9,
    emojiAnalogy: "3 + 3 + 3 = 9 ⭐",
    explanation: "3 nhân 3 bằng 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_080",
    problemStr: "4 x 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "2 + 2 + 2 + 2 = 8 🚗",
    explanation: "4 nhân 2 bằng 8.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_081",
    problemStr: "5 x 1 = ?",
    correctAnswer: 5,
    emojiAnalogy: "5 x 1 = 5 ✋",
    explanation: "Bất kỳ số nào nhân 1 cũng bằng chính nó.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_082",
    problemStr: "3 x 2 = ?",
    correctAnswer: 6,
    emojiAnalogy: "2 + 2 + 2 = 6 🍭",
    explanation: "3 nhân 2 bằng 6.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_083",
    problemStr: "2 x 2 = ?",
    correctAnswer: 4,
    emojiAnalogy: "2 + 2 = 4 🐣",
    explanation: "2 nhân 2 bằng 4.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_084",
    problemStr: "Hình vuông có mấy cạnh?",
    correctAnswer: 4,
    emojiAnalogy: "Hình vuông ⏹️ có 4 cạnh bằng nhau",
    explanation: "Hình vuông có đúng 4 cạnh và 4 góc vuông.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_085",
    problemStr: "Hình tam giác có mấy góc?",
    correctAnswer: 3,
    emojiAnalogy: "Hình tam giác 🔺 có 3 đỉnh góc",
    explanation: "Hình tam giác có 3 cạnh và 3 góc!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_086",
    problemStr: "Một con mèo có mấy cái chân?",
    correctAnswer: 4,
    emojiAnalogy: "🐱 4 chân",
    explanation: "Con mèo có 4 cái chân!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_087",
    problemStr: "2 con gà có tất cả mấy chân?",
    correctAnswer: 4,
    emojiAnalogy: "🐔(2 chân) + 🐔(2 chân) = 4 chân",
    explanation: "Mỗi con gà có 2 chân, 2 con gà có: 2 + 2 = 4 chân!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_088",
    problemStr: "Một bàn tay có mấy ngón?",
    correctAnswer: 5,
    emojiAnalogy: "🖐️ = 5 ngón tay",
    explanation: "Một bàn tay người có 5 ngón tay!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_089",
    problemStr: "Hình ngôi sao 5 cánh có mấy đỉnh?",
    correctAnswer: 5,
    emojiAnalogy: "⭐ = 5 đỉnh cánh",
    explanation: "Ngôi sao 5 cánh có đúng 5 đỉnh!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_090",
    problemStr: "Hình tròn có mấy cạnh thẳng?",
    correctAnswer: 0,
    emojiAnalogy: "⭕ = 0 cạnh thẳng (Giơ nắm tay ✊)",
    explanation: "Hình tròn là đường cong khép kín, có 0 cạnh thẳng (giơ nắm tay 0 ngón)!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Trung bình",
  },
  {
    id: "g1_091",
    problemStr: "Số liền sau của số 6 là?",
    correctAnswer: 7,
    emojiAnalogy: "6 ➡️ 7 🌟",
    explanation: "Số liền sau của 6 là 6 + 1 = 7.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_092",
    problemStr: "Số liền trước của số 10 là?",
    correctAnswer: 9,
    emojiAnalogy: "9 ⬅️ 10 🎯",
    explanation: "Số liền trước của 10 là 10 - 1 = 9.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_093",
    problemStr: "Có 3 con thỏ, mỗi con có 2 tai. Hỏi có mấy tai?",
    correctAnswer: 6,
    emojiAnalogy: "🐰🐰🐰 = 2 + 2 + 2 = 6 tai",
    explanation: "3 x 2 = 6 cái tai thỏ.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Trung bình",
  },
  {
    id: "g1_094",
    problemStr: "Hình chữ nhật có mấy góc vuông?",
    correctAnswer: 4,
    emojiAnalogy: "Rectangle 📄 có 4 góc vuông",
    explanation: "Hình chữ nhật có 4 góc vuông.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g1_095",
    problemStr: "Mẹ mua 7 quả trứng, rán 3 quả. Còn lại mấy quả?",
    correctAnswer: 4,
    emojiAnalogy: "7 🥚 - 3 🥚 = 4 🥚",
    explanation: "7 - 3 = 4 quả trứng còn lại.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_096",
    problemStr: "Nam có 4 viên bi, Minh cho Nam 3 viên bi nữa. Nam có mấy viên bi?",
    correctAnswer: 7,
    emojiAnalogy: "4 🔵 + 3 🔵 = 7 🔵",
    explanation: "4 + 3 = 7 viên bi.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_097",
    problemStr: "2 x 1 = ?",
    correctAnswer: 2,
    emojiAnalogy: "2 x 1 = 2 ✌️",
    explanation: "2 nhân 1 bằng 2.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_098",
    problemStr: "7 x 1 = ?",
    correctAnswer: 7,
    emojiAnalogy: "7 x 1 = 7 ⭐",
    explanation: "7 nhân 1 bằng 7.",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g1_099",
    problemStr: "Có 5 cái kẹo, chia cho Nam 5 cái. Hỏi còn mấy cái kẹo?",
    correctAnswer: 0,
    emojiAnalogy: "5 - 5 = 0 🍬 (Nắm tay ✊)",
    explanation: "5 - 5 = 0 chiếc kẹo!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Cộng trừ cơ bản",
    difficulty: "Dễ",
  },
  {
    id: "g1_100",
    problemStr: "2 x 0 = ?",
    correctAnswer: 0,
    emojiAnalogy: "Bất kỳ số nào nhân 0 đều bằng 0 ✊",
    explanation: "2 x 0 = 0 (Giơ nắm đấm 0 ngón)!",
    gradeLevel: "Lớp 1 - 2",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
];
