import { MathQuestion } from "./mathQuestionTypes";

export const GRADE_3_5_QUESTIONS: MathQuestion[] = [
  // --- PHÉP CHIA BẢNG CỬU CHƯƠNG (1 - 35) ---
  {
    id: "g3_001",
    problemStr: "36 : 4 = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 kẹo chia 4 bạn = 9 🍬/bạn",
    explanation: "36 chia 4 bằng 9 (vì 9 x 4 = 36).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_002",
    problemStr: "56 : 8 = ?",
    correctAnswer: 7,
    emojiAnalogy: "7 x 8 = 56 ➡️ 56 : 8 = 7 🎯",
    explanation: "56 chia 8 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_003",
    problemStr: "72 : 9 = ?",
    correctAnswer: 8,
    emojiAnalogy: "8 x 9 = 72 ➡️ 72 : 9 = 8 ⚡",
    explanation: "72 chia 9 bằng 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_004",
    problemStr: "48 : 6 = ?",
    correctAnswer: 8,
    emojiAnalogy: "6 x 8 = 48 ➡️ 48 : 6 = 8 🚀",
    explanation: "48 chia 6 bằng 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_005",
    problemStr: "63 : 7 = ?",
    correctAnswer: 9,
    emojiAnalogy: "7 x 9 = 63 ➡️ 63 : 7 = 9 🌟",
    explanation: "63 chia 7 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_006",
    problemStr: "45 : 5 = ?",
    correctAnswer: 9,
    emojiAnalogy: "5 x 9 = 45 ➡️ 45 : 5 = 9 🍎",
    explanation: "45 chia 5 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_007",
    problemStr: "35 : 5 = ?",
    correctAnswer: 7,
    emojiAnalogy: "5 x 7 = 35 ➡️ 35 : 5 = 7 🍉",
    explanation: "35 chia 5 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_008",
    problemStr: "81 : 9 = ?",
    correctAnswer: 9,
    emojiAnalogy: "9 x 9 = 81 ➡️ 81 : 9 = 9 💎",
    explanation: "81 chia 9 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_009",
    problemStr: "28 : 4 = ?",
    correctAnswer: 7,
    emojiAnalogy: "4 x 7 = 28 ➡️ 28 : 4 = 7 🍪",
    explanation: "28 chia 4 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_010",
    problemStr: "54 : 6 = ?",
    correctAnswer: 9,
    emojiAnalogy: "6 x 9 = 54 ➡️ 54 : 6 = 9 🎈",
    explanation: "54 chia 6 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_011",
    problemStr: "42 : 7 = ?",
    correctAnswer: 6,
    emojiAnalogy: "7 x 6 = 42 ➡️ 42 : 7 = 6 🍓",
    explanation: "42 chia 7 bằng 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_012",
    problemStr: "64 : 8 = ?",
    correctAnswer: 8,
    emojiAnalogy: "8 x 8 = 64 ➡️ 64 : 8 = 8 ⭐",
    explanation: "64 chia 8 bằng 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_013",
    problemStr: "49 : 7 = ?",
    correctAnswer: 7,
    emojiAnalogy: "7 x 7 = 49 ➡️ 49 : 7 = 7 🌸",
    explanation: "49 chia 7 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_014",
    problemStr: "32 : 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 x 8 = 32 ➡️ 32 : 4 = 8 🍧",
    explanation: "32 chia 4 bằng 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_015",
    problemStr: "27 : 3 = ?",
    correctAnswer: 9,
    emojiAnalogy: "3 x 9 = 27 ➡️ 27 : 3 = 9 🌻",
    explanation: "27 chia 3 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_016",
    problemStr: "40 : 8 = ?",
    correctAnswer: 5,
    emojiAnalogy: "8 x 5 = 40 ➡️ 40 : 8 = 5 ✋",
    explanation: "40 chia 8 bằng 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_017",
    problemStr: "30 : 6 = ?",
    correctAnswer: 5,
    emojiAnalogy: "6 x 5 = 30 ➡️ 30 : 6 = 5 🎲",
    explanation: "30 chia 6 bằng 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_018",
    problemStr: "24 : 8 = ?",
    correctAnswer: 3,
    emojiAnalogy: "8 x 3 = 24 ➡️ 24 : 8 = 3 🐥",
    explanation: "24 chia 8 bằng 3.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_019",
    problemStr: "18 : 2 = ?",
    correctAnswer: 9,
    emojiAnalogy: "2 x 9 = 18 ➡️ 18 : 2 = 9 🚗",
    explanation: "18 chia 2 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_020",
    problemStr: "16 : 4 = ?",
    correctAnswer: 4,
    emojiAnalogy: "4 x 4 = 16 ➡️ 16 : 4 = 4 ⏹️",
    explanation: "16 chia 4 bằng 4.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_021",
    problemStr: "100 : 10 = ?",
    correctAnswer: 10,
    emojiAnalogy: "10 x 10 = 100 ➡️ 100 : 10 = 10 🔟",
    explanation: "100 chia 10 bằng 10.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_022",
    problemStr: "70 : 10 = ?",
    correctAnswer: 7,
    emojiAnalogy: "70 : 10 = 7 🎯",
    explanation: "70 chia 10 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_023",
    problemStr: "60 : 10 = ?",
    correctAnswer: 6,
    emojiAnalogy: "60 : 10 = 6 🌟",
    explanation: "60 chia 10 bằng 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_024",
    problemStr: "90 : 10 = ?",
    correctAnswer: 9,
    emojiAnalogy: "90 : 10 = 9 🚀",
    explanation: "90 chia 10 bằng 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_025",
    problemStr: "50 : 10 = ?",
    correctAnswer: 5,
    emojiAnalogy: "50 : 10 = 5 ✋",
    explanation: "50 chia 10 bằng 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_026",
    problemStr: "21 : 3 = ?",
    correctAnswer: 7,
    emojiAnalogy: "3 x 7 = 21 ➡️ 21 : 3 = 7 🍓",
    explanation: "21 chia 3 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_027",
    problemStr: "14 : 2 = ?",
    correctAnswer: 7,
    emojiAnalogy: "2 x 7 = 14 ➡️ 14 : 2 = 7 🍒",
    explanation: "14 chia 2 bằng 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_028",
    problemStr: "36 : 6 = ?",
    correctAnswer: 6,
    emojiAnalogy: "6 x 6 = 36 ➡️ 36 : 6 = 6 🎲",
    explanation: "36 chia 6 bằng 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_029",
    problemStr: "25 : 5 = ?",
    correctAnswer: 5,
    emojiAnalogy: "5 x 5 = 25 ➡️ 25 : 5 = 5 🖐️",
    explanation: "25 chia 5 bằng 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_030",
    problemStr: "12 : 3 = ?",
    correctAnswer: 4,
    emojiAnalogy: "3 x 4 = 12 ➡️ 12 : 3 = 4 🍏",
    explanation: "12 chia 3 bằng 4.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_031",
    problemStr: "0 : 8 = ?",
    correctAnswer: 0,
    emojiAnalogy: "0 chia cho bất kỳ số khác 0 nào đều = 0 ✊",
    explanation: "0 chia 8 bằng 0 (Giơ nắm đấm ✊)!",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_032",
    problemStr: "15 : 5 = ?",
    correctAnswer: 3,
    emojiAnalogy: "5 x 3 = 15 ➡️ 15 : 5 = 3 🍉",
    explanation: "15 chia 5 bằng 3.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_033",
    problemStr: "18 : 6 = ?",
    correctAnswer: 3,
    emojiAnalogy: "6 x 3 = 18 ➡️ 18 : 6 = 3 🍫",
    explanation: "18 chia 6 bằng 3.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_034",
    problemStr: "20 : 5 = ?",
    correctAnswer: 4,
    emojiAnalogy: "5 x 4 = 20 ➡️ 20 : 5 = 4 🚙",
    explanation: "20 chia 5 bằng 4.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_035",
    problemStr: "24 : 6 = ?",
    correctAnswer: 4,
    emojiAnalogy: "6 x 4 = 24 ➡️ 24 : 6 = 4 🍬",
    explanation: "24 chia 6 bằng 4.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },

  // --- PHÂN SỐ CƠ BẢN (36 - 60) ---
  {
    id: "g3_036",
    problemStr: "1/2 của 16 = ?",
    correctAnswer: 8,
    emojiAnalogy: "16 quả cam chia đôi = 8 🍊",
    explanation: "Một nửa (1/2) của 16 là 16 : 2 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_037",
    problemStr: "1/3 của 27 = ?",
    correctAnswer: 9,
    emojiAnalogy: "27 : 3 = 9 🌟",
    explanation: "Một phần ba của 27 là 27 : 3 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_038",
    problemStr: "1/4 của 28 = ?",
    correctAnswer: 7,
    emojiAnalogy: "28 : 4 = 7 🎯",
    explanation: "Một phần tư của 28 là 28 : 4 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_039",
    problemStr: "1/5 của 35 = ?",
    correctAnswer: 7,
    emojiAnalogy: "35 : 5 = 7 🍪",
    explanation: "Một phần năm của 35 là 35 : 5 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_040",
    problemStr: "1/2 của 18 = ?",
    correctAnswer: 9,
    emojiAnalogy: "18 : 2 = 9 🚀",
    explanation: "1/2 của 18 là 18 : 2 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_041",
    problemStr: "1/3 của 15 = ?",
    correctAnswer: 5,
    emojiAnalogy: "15 : 3 = 5 🍎",
    explanation: "1/3 của 15 là 15 : 3 = 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_042",
    problemStr: "1/4 của 36 = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 💎",
    explanation: "1/4 của 36 là 36 : 4 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_043",
    problemStr: "1/6 của 48 = ?",
    correctAnswer: 8,
    emojiAnalogy: "48 : 6 = 8 ⚡",
    explanation: "1/6 của 48 là 48 : 6 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_044",
    problemStr: "1/2 của 20 = ?",
    correctAnswer: 10,
    emojiAnalogy: "20 : 2 = 10 🔟",
    explanation: "1/2 của 20 là 20 : 2 = 10.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Dễ",
  },
  {
    id: "g3_045",
    problemStr: "1/3 của 24 = ?",
    correctAnswer: 8,
    emojiAnalogy: "24 : 3 = 8 🎈",
    explanation: "1/3 của 24 là 24 : 3 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_046",
    problemStr: "1/5 của 45 = ?",
    correctAnswer: 9,
    emojiAnalogy: "45 : 5 = 9 🍉",
    explanation: "1/5 của 45 là 45 : 5 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_047",
    problemStr: "1/4 của 24 = ?",
    correctAnswer: 6,
    emojiAnalogy: "24 : 4 = 6 🍓",
    explanation: "1/4 của 24 là 24 : 4 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_048",
    problemStr: "1/7 của 42 = ?",
    correctAnswer: 6,
    emojiAnalogy: "42 : 7 = 6 🌸",
    explanation: "1/7 của 42 là 42 : 7 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_049",
    problemStr: "1/8 của 56 = ?",
    correctAnswer: 7,
    emojiAnalogy: "56 : 8 = 7 ⭐",
    explanation: "1/8 của 56 là 56 : 8 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_050",
    problemStr: "1/9 của 72 = ?",
    correctAnswer: 8,
    emojiAnalogy: "72 : 9 = 8 🍰",
    explanation: "1/9 của 72 là 72 : 9 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_051",
    problemStr: "1/2 của 14 = ?",
    correctAnswer: 7,
    emojiAnalogy: "14 : 2 = 7 🍒",
    explanation: "1/2 của 14 là 14 : 2 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Dễ",
  },
  {
    id: "g3_052",
    problemStr: "1/3 của 18 = ?",
    correctAnswer: 6,
    emojiAnalogy: "18 : 3 = 6 🚗",
    explanation: "1/3 của 18 là 18 : 3 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Dễ",
  },
  {
    id: "g3_053",
    problemStr: "1/4 của 32 = ?",
    correctAnswer: 8,
    emojiAnalogy: "32 : 4 = 8 🍦",
    explanation: "1/4 của 32 là 32 : 4 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_054",
    problemStr: "1/5 của 50 = ?",
    correctAnswer: 10,
    emojiAnalogy: "50 : 5 = 10 🔟",
    explanation: "1/5 của 50 là 50 : 5 = 10.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_055",
    problemStr: "1/6 của 36 = ?",
    correctAnswer: 6,
    emojiAnalogy: "36 : 6 = 6 🎲",
    explanation: "1/6 của 36 là 36 : 6 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_056",
    problemStr: "1/7 của 63 = ?",
    correctAnswer: 9,
    emojiAnalogy: "63 : 7 = 9 🌟",
    explanation: "1/7 của 63 là 63 : 7 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_057",
    problemStr: "1/8 của 64 = ?",
    correctAnswer: 8,
    emojiAnalogy: "64 : 8 = 8 🎯",
    explanation: "1/8 của 64 là 64 : 8 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_058",
    problemStr: "1/9 của 81 = ?",
    correctAnswer: 9,
    emojiAnalogy: "81 : 9 = 9 💎",
    explanation: "1/9 của 81 là 81 : 9 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_059",
    problemStr: "1/10 của 80 = ?",
    correctAnswer: 8,
    emojiAnalogy: "80 : 10 = 8 ⚡",
    explanation: "1/10 của 80 là 80 : 10 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Dễ",
  },
  {
    id: "g3_060",
    problemStr: "1/10 của 100 = ?",
    correctAnswer: 10,
    emojiAnalogy: "100 : 10 = 10 🔟",
    explanation: "1/10 của 100 bằng 10.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Dễ",
  },

  // --- BIỂU THỨC TÍNH TOÁN & TÌM X (61 - 80) ---
  {
    id: "g3_061",
    problemStr: "Tìm x: x x 6 = 48",
    correctAnswer: 8,
    emojiAnalogy: "x = 48 : 6 = 8 💡",
    explanation: "Thừa số = Tích chia thừa số kia: 48 : 6 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g3_062",
    problemStr: "Tìm x: 72 : x = 9",
    correctAnswer: 8,
    emojiAnalogy: "x = 72 : 9 = 8 🔑",
    explanation: "Số chia = Số bị chia chia thương: 72 : 9 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g3_063",
    problemStr: "Tìm x: x : 3 = 3",
    correctAnswer: 9,
    emojiAnalogy: "x = 3 x 3 = 9 🚪",
    explanation: "Số bị chia = Thương nhân số chia: 3 x 3 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g3_064",
    problemStr: "(12 + 18) : 5 = ?",
    correctAnswer: 6,
    emojiAnalogy: "30 : 5 = 6 🌟",
    explanation: "Tính trong ngoặc trước: 12 + 18 = 30, sau đó 30 : 5 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_065",
    problemStr: "5 x 4 - 12 = ?",
    correctAnswer: 8,
    emojiAnalogy: "20 - 12 = 8 🎯",
    explanation: "Nhân chia trước cộng trừ sau: 5 x 4 = 20, 20 - 12 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_066",
    problemStr: "8 x 3 - 15 = ?",
    correctAnswer: 9,
    emojiAnalogy: "24 - 15 = 9 🚀",
    explanation: "8 x 3 = 24, 24 - 15 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_067",
    problemStr: "50 : 5 - 3 = ?",
    correctAnswer: 7,
    emojiAnalogy: "10 - 3 = 7 🍰",
    explanation: "50 : 5 = 10, 10 - 3 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_068",
    problemStr: "6 x 6 : 4 = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 💎",
    explanation: "6 x 6 = 36, 36 : 4 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_069",
    problemStr: "Tìm x: 4 x x = 28",
    correctAnswer: 7,
    emojiAnalogy: "x = 28 : 4 = 7 ⭐",
    explanation: "x = 28 : 4 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g3_070",
    problemStr: "Tìm x: 54 : x = 6",
    correctAnswer: 9,
    emojiAnalogy: "x = 54 : 6 = 9 🎈",
    explanation: "x = 54 : 6 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g3_071",
    problemStr: "(45 - 9) : 4 = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 🍉",
    explanation: "45 - 9 = 36; 36 : 4 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_072",
    problemStr: "(20 + 28) : 6 = ?",
    correctAnswer: 8,
    emojiAnalogy: "48 : 6 = 8 ⚡",
    explanation: "20 + 28 = 48; 48 : 6 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_073",
    problemStr: "7 x 4 - 21 = ?",
    correctAnswer: 7,
    emojiAnalogy: "28 - 21 = 7 🌸",
    explanation: "7 x 4 = 28, 28 - 21 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_074",
    problemStr: "3 x 3 x 1 = ?",
    correctAnswer: 9,
    emojiAnalogy: "9 x 1 = 9 🌟",
    explanation: "3 x 3 = 9, 9 x 1 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_075",
    problemStr: "2 x 2 x 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 x 2 = 8 🎲",
    explanation: "2 x 2 = 4, 4 x 2 = 8.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_076",
    problemStr: "Tìm x: 9 x x = 81",
    correctAnswer: 9,
    emojiAnalogy: "x = 81 : 9 = 9 🎯",
    explanation: "x = 81 : 9 = 9.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g3_077",
    problemStr: "Tìm x: 42 : x = 7",
    correctAnswer: 6,
    emojiAnalogy: "x = 42 : 7 = 6 🍓",
    explanation: "x = 42 : 7 = 6.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g3_078",
    problemStr: "4 x 5 : 2 = ?",
    correctAnswer: 10,
    emojiAnalogy: "20 : 2 = 10 🔟",
    explanation: "4 x 5 = 20; 20 : 2 = 10.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_079",
    problemStr: "(15 + 25) : 8 = ?",
    correctAnswer: 5,
    emojiAnalogy: "40 : 8 = 5 ✋",
    explanation: "15 + 25 = 40; 40 : 8 = 5.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },
  {
    id: "g3_080",
    problemStr: "6 x 7 - 35 = ?",
    correctAnswer: 7,
    emojiAnalogy: "42 - 35 = 7 🍒",
    explanation: "6 x 7 = 42, 42 - 35 = 7.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Trung bình",
  },

  // --- HÌNH HỌC, CHU VI & TOÁN ĐỐ LOGIC (81 - 100) ---
  {
    id: "g3_081",
    problemStr: "Cạnh hình vuông có chu vi 20cm là?",
    correctAnswer: 5,
    emojiAnalogy: "20 : 4 = 5 cm ⏹️",
    explanation: "Cạnh hình vuông = Chu vi : 4 = 20 : 4 = 5 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_082",
    problemStr: "Cạnh hình vuông có chu vi 28cm là?",
    correctAnswer: 7,
    emojiAnalogy: "28 : 4 = 7 cm ⏹️",
    explanation: "28 : 4 = 7 cm.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_083",
    problemStr: "Cạnh hình vuông có chu vi 36cm là?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 cm ⏹️",
    explanation: "36 : 4 = 9 cm.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_084",
    problemStr: "Cạnh tam giác đều có chu vi 18cm là?",
    correctAnswer: 6,
    emojiAnalogy: "18 : 3 = 6 cm 🔺",
    explanation: "Tam giác đều có 3 cạnh bằng nhau: 18 : 3 = 6 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_085",
    problemStr: "Cạnh tam giác đều có chu vi 24cm là?",
    correctAnswer: 8,
    emojiAnalogy: "24 : 3 = 8 cm 🔺",
    explanation: "24 : 3 = 8 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_086",
    problemStr: "Cạnh tam giác đều có chu vi 27cm là?",
    correctAnswer: 9,
    emojiAnalogy: "27 : 3 = 9 cm 🔺",
    explanation: "27 : 3 = 9 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_087",
    problemStr: "Cạnh hình thoi có chu vi 32cm là?",
    correctAnswer: 8,
    emojiAnalogy: "32 : 4 = 8 cm 🔷",
    explanation: "Hình thoi có 4 cạnh bằng nhau: 32 : 4 = 8 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_088",
    problemStr: "Cạnh hình lục giác đều chu vi 30cm là?",
    correctAnswer: 5,
    emojiAnalogy: "30 : 6 = 5 cm ⬡",
    explanation: "Hình lục giác đều có 6 cạnh bằng nhau: 30 : 6 = 5 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Thử thách",
  },
  {
    id: "g3_089",
    problemStr: "Một tuần lễ có mấy ngày?",
    correctAnswer: 7,
    emojiAnalogy: "Thứ 2 đến Chủ nhật = 7 ngày 📅",
    explanation: "Một tuần có đúng 7 ngày.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g3_090",
    problemStr: "Hình ngũ giác có mấy cạnh?",
    correctAnswer: 5,
    emojiAnalogy: "Ngũ giác (Pentagon) = 5 cạnh ⬟",
    explanation: "Hình ngũ giác có 5 cạnh và 5 góc.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g3_091",
    problemStr: "Hình lục giác có mấy đỉnh?",
    correctAnswer: 6,
    emojiAnalogy: "Lục giác (Hexagon) = 6 đỉnh ⬡",
    explanation: "Hình lục giác có 6 đỉnh.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g3_092",
    problemStr: "Hình lập phương có mấy mặt?",
    correctAnswer: 6,
    emojiAnalogy: "Khối xúc xắc 🎲 có 6 mặt",
    explanation: "Hình lập phương có đúng 6 mặt vuông bằng nhau.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Trung bình",
  },
  {
    id: "g3_093",
    problemStr: "Hình lập phương có mấy đỉnh?",
    correctAnswer: 8,
    emojiAnalogy: "4 đỉnh trên + 4 đỉnh dưới = 8 đỉnh 📦",
    explanation: "Hình lập phương có đúng 8 đỉnh nhọn.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Trung bình",
  },
  {
    id: "g3_094",
    problemStr: "Nửa chu vi HCN có chiều dài 5cm, rộng 3cm là?",
    correctAnswer: 8,
    emojiAnalogy: "5 + 3 = 8 cm 📄",
    explanation: "Nửa chu vi hình chữ nhật = Dài + Rộng = 5 + 3 = 8 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_095",
    problemStr: "Nửa chu vi HCN có chiều dài 6cm, rộng 4cm là?",
    correctAnswer: 10,
    emojiAnalogy: "6 + 4 = 10 cm 🔟",
    explanation: "6 + 4 = 10 cm.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Trung bình",
  },
  {
    id: "g3_096",
    problemStr: "Có 40 cái kẹo chia đều cho 5 bạn. Mỗi bạn được?",
    correctAnswer: 8,
    emojiAnalogy: "40 : 5 = 8 🍬",
    explanation: "40 chia cho 5 bằng 8 chiếc kẹo.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_097",
    problemStr: "Lớp có 36 học sinh chia thành 4 tổ đều nhau. Mỗi tổ có?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 bạn 🎒",
    explanation: "36 : 4 = 9 học sinh mỗi tổ.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Nhân & Chia",
    difficulty: "Dễ",
  },
  {
    id: "g3_098",
    problemStr: "Số góc vuông trong một hình vuông là?",
    correctAnswer: 4,
    emojiAnalogy: "⏹️ = 4 góc vuông 90°",
    explanation: "Hình vuông có 4 góc vuông.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Dễ",
  },
  {
    id: "g3_099",
    problemStr: "Số đỉnh của hình chóp tứ giác là?",
    correctAnswer: 5,
    emojiAnalogy: "1 đỉnh chóp + 4 đỉnh đáy = 5 đỉnh ⛺",
    explanation: "Hình chóp tứ giác có 1 đỉnh trên và 4 đỉnh ở đáy, tổng là 5 đỉnh.",
    gradeLevel: "Lớp 3 - 5",
    topic: "Đếm hình & Toán đố",
    difficulty: "Thử thách",
  },
  {
    id: "g3_100",
    problemStr: "Cạnh hình vuông có diện tích 49cm² là?",
    correctAnswer: 7,
    emojiAnalogy: "7 x 7 = 49 cm² ➡️ Cạnh = 7 cm 📐",
    explanation: "Diện tích hình vuông = cạnh x cạnh = 49 ➡️ cạnh là 7 (cm).",
    gradeLevel: "Lớp 3 - 5",
    topic: "Phân số & Chu vi",
    difficulty: "Thử thách",
  },
];
