import { MathQuestion } from "./mathQuestionTypes";

export const GRADE_7_QUESTIONS: MathQuestion[] = [
  // --- CĂN BẬC HAI SỐ HỌC (1 - 30) ---
  {
    id: "g7_001",
    problemStr: "Căn bậc hai: √49 = ?",
    correctAnswer: 7,
    emojiAnalogy: "√49 = 7 vì 7² = 49 🌿",
    explanation: "Căn bậc hai số học của 49 là 7 (vì 7 > 0 và 7 x 7 = 49).",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_002",
    problemStr: "Căn bậc hai: √64 = ?",
    correctAnswer: 8,
    emojiAnalogy: "√64 = 8 vì 8² = 64 💎",
    explanation: "Căn bậc hai số học của 64 là 8 (8 x 8 = 64).",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_003",
    problemStr: "Căn bậc hai: √81 = ?",
    correctAnswer: 9,
    emojiAnalogy: "√81 = 9 vì 9² = 81 🌟",
    explanation: "Căn bậc hai số học của 81 là 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_004",
    problemStr: "Căn bậc hai: √100 = ?",
    correctAnswer: 10,
    emojiAnalogy: "√100 = 10 vì 10² = 100 🔟",
    explanation: "Căn bậc hai số học của 100 là 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_005",
    problemStr: "Căn bậc hai: √36 = ?",
    correctAnswer: 6,
    emojiAnalogy: "√36 = 6 vì 6² = 36 🎲",
    explanation: "Căn bậc hai số học của 36 là 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_006",
    problemStr: "Căn bậc hai: √25 = ?",
    correctAnswer: 5,
    emojiAnalogy: "√25 = 5 vì 5² = 25 🖐️",
    explanation: "Căn bậc hai số học của 25 là 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_007",
    problemStr: "Căn bậc hai: √16 = ?",
    correctAnswer: 4,
    emojiAnalogy: "√16 = 4 vì 4² = 16 ⏹️",
    explanation: "Căn bậc hai số học của 16 là 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_008",
    problemStr: "Căn bậc hai: √9 = ?",
    correctAnswer: 3,
    emojiAnalogy: "√9 = 3 vì 3² = 9 🔺",
    explanation: "Căn bậc hai số học của 9 là 3.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_009",
    problemStr: "Căn bậc hai: √4 = ?",
    correctAnswer: 2,
    emojiAnalogy: "√4 = 2 vì 2² = 4 ✌️",
    explanation: "Căn bậc hai số học của 4 là 2.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_010",
    problemStr: "Căn bậc hai: √1 = ?",
    correctAnswer: 1,
    emojiAnalogy: "√1 = 1 vì 1² = 1 ☝️",
    explanation: "Căn bậc hai số học của 1 là 1.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_011",
    problemStr: "Căn bậc hai: √0 = ?",
    correctAnswer: 0,
    emojiAnalogy: "√0 = 0 ✊",
    explanation: "Căn bậc hai số học của 0 là 0 (Giơ nắm tay ✊).",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_012",
    problemStr: "Tính: √49 + √9 = ?",
    correctAnswer: 10,
    emojiAnalogy: "7 + 3 = 10 🔟",
    explanation: "√49 = 7 và √9 = 3, 7 + 3 = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_013",
    problemStr: "Tính: √100 - √16 = ?",
    correctAnswer: 6,
    emojiAnalogy: "10 - 4 = 6 🌟",
    explanation: "√100 = 10 và √16 = 4 ➡️ 10 - 4 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_014",
    problemStr: "Tính: √64 - √25 = ?",
    correctAnswer: 3,
    emojiAnalogy: "8 - 5 = 3 🍓",
    explanation: "8 - 5 = 3.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_015",
    problemStr: "Tính: √81 - √4 = ?",
    correctAnswer: 7,
    emojiAnalogy: "9 - 2 = 7 🎯",
    explanation: "9 - 2 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_016",
    problemStr: "Tính: √36 + √4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "6 + 2 = 8 ⚡",
    explanation: "6 + 2 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },
  {
    id: "g7_017",
    problemStr: "Tính: √16 x √4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "4 x 2 = 8 🍰",
    explanation: "4 x 2 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_018",
    problemStr: "Tính: √81 : √9 = ?",
    correctAnswer: 3,
    emojiAnalogy: "9 : 3 = 3 🍉",
    explanation: "9 : 3 = 3.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_019",
    problemStr: "Tính: √64 : √4 = ?",
    correctAnswer: 4,
    emojiAnalogy: "8 : 2 = 4 🍏",
    explanation: "8 : 2 = 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_020",
    problemStr: "Tính: √100 : √4 = ?",
    correctAnswer: 5,
    emojiAnalogy: "10 : 2 = 5 🖐️",
    explanation: "10 : 2 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_021",
    problemStr: "Tính: (√25)² - 18 = ?",
    correctAnswer: 7,
    emojiAnalogy: "25 - 18 = 7 🌸",
    explanation: "(√25)² = 25, 25 - 18 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_022",
    problemStr: "Tính: (√36)² - 30 = ?",
    correctAnswer: 6,
    emojiAnalogy: "36 - 30 = 6 🎲",
    explanation: "36 - 30 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Trung bình",
  },
  {
    id: "g7_023",
    problemStr: "Tính: √144 : 2 = ?",
    correctAnswer: 6,
    emojiAnalogy: "12 : 2 = 6 🚙",
    explanation: "√144 = 12, 12 : 2 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_024",
    problemStr: "Tính: √169 - 5 = ?",
    correctAnswer: 8,
    emojiAnalogy: "13 - 5 = 8 🎈",
    explanation: "√169 = 13, 13 - 5 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_025",
    problemStr: "Tính: √196 : 2 = ?",
    correctAnswer: 7,
    emojiAnalogy: "14 : 2 = 7 🍒",
    explanation: "√196 = 14, 14 : 2 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_026",
    problemStr: "Tính: √225 : 3 = ?",
    correctAnswer: 5,
    emojiAnalogy: "15 : 3 = 5 🖐️",
    explanation: "√225 = 15, 15 : 3 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_027",
    problemStr: "Tính: √256 : 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "16 : 2 = 8 ⚡",
    explanation: "√256 = 16, 16 : 2 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_028",
    problemStr: "Tính: √400 : 4 = ?",
    correctAnswer: 5,
    emojiAnalogy: "20 : 4 = 5 🖐️",
    explanation: "√400 = 20, 20 : 4 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_029",
    problemStr: "Tính: √121 - 2 = ?",
    correctAnswer: 9,
    emojiAnalogy: "11 - 2 = 9 🌟",
    explanation: "√121 = 11, 11 - 2 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Thử thách",
  },
  {
    id: "g7_030",
    problemStr: "Tính: √25 + √16 = ?",
    correctAnswer: 9,
    emojiAnalogy: "5 + 4 = 9 🚀",
    explanation: "5 + 4 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Căn bậc hai",
    difficulty: "Dễ",
  },

  // --- GIÁ TRỊ TUYỆT ĐỐI (31 - 50) ---
  {
    id: "g7_031",
    problemStr: "Giá trị tuyệt đối: |-6| = ?",
    correctAnswer: 6,
    emojiAnalogy: "Khoảng cách đến 0 là 6 📏",
    explanation: "Giá trị tuyệt đối của số âm bằng số đối: |-6| = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_032",
    problemStr: "Giá trị tuyệt đối: |-9| = ?",
    correctAnswer: 9,
    emojiAnalogy: "|-9| = 9 🌟",
    explanation: "|-9| = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_033",
    problemStr: "Giá trị tuyệt đối: |-8| = ?",
    correctAnswer: 8,
    emojiAnalogy: "|-8| = 8 🎈",
    explanation: "|-8| = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_034",
    problemStr: "Giá trị tuyệt đối: |-7| = ?",
    correctAnswer: 7,
    emojiAnalogy: "|-7| = 7 🎯",
    explanation: "|-7| = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_035",
    problemStr: "Tính: |-5| + 3 = ?",
    correctAnswer: 8,
    emojiAnalogy: "5 + 3 = 8 🍪",
    explanation: "|-5| = 5, 5 + 3 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_036",
    problemStr: "Tính: |-10| - 2 = ?",
    correctAnswer: 8,
    emojiAnalogy: "10 - 2 = 8 ⚡",
    explanation: "10 - 2 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_037",
    problemStr: "Tính: |-3| x 3 = ?",
    correctAnswer: 9,
    emojiAnalogy: "3 x 3 = 9 💎",
    explanation: "3 x 3 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_038",
    problemStr: "Tính: |7 - 12| = ?",
    correctAnswer: 5,
    emojiAnalogy: "|-5| = 5 🖐️",
    explanation: "7 - 12 = -5 ➡️ |-5| = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_039",
    problemStr: "Tính: |4 - 10| = ?",
    correctAnswer: 6,
    emojiAnalogy: "|-6| = 6 🎲",
    explanation: "4 - 10 = -6 ➡️ |-6| = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_040",
    problemStr: "Tính: |2 - 9| = ?",
    correctAnswer: 7,
    emojiAnalogy: "|-7| = 7 🌸",
    explanation: "2 - 9 = -7 ➡️ |-7| = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_041",
    problemStr: "Tính: |-8| - |-2| = ?",
    correctAnswer: 6,
    emojiAnalogy: "8 - 2 = 6 🚙",
    explanation: "8 - 2 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_042",
    problemStr: "Tính: |-4| + |-3| = ?",
    correctAnswer: 7,
    emojiAnalogy: "4 + 3 = 7 🍉",
    explanation: "4 + 3 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_043",
    problemStr: "Tính: |-6| + |-4| = ?",
    correctAnswer: 10,
    emojiAnalogy: "6 + 4 = 10 🔟",
    explanation: "6 + 4 = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_044",
    problemStr: "Tính: |-15| : 3 = ?",
    correctAnswer: 5,
    emojiAnalogy: "15 : 3 = 5 🖐️",
    explanation: "15 : 3 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_045",
    problemStr: "Tính: |-24| : 4 = ?",
    correctAnswer: 6,
    emojiAnalogy: "24 : 4 = 6 🍰",
    explanation: "24 : 4 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_046",
    problemStr: "Tính: |-32| : 4 = ?",
    correctAnswer: 8,
    emojiAnalogy: "32 : 4 = 8 ⚡",
    explanation: "32 : 4 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_047",
    problemStr: "Tính: |-36| : 4 = ?",
    correctAnswer: 9,
    emojiAnalogy: "36 : 4 = 9 🌟",
    explanation: "36 : 4 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_048",
    problemStr: "Tìm x dương: |x| = 7",
    correctAnswer: 7,
    emojiAnalogy: "x = 7 🎯",
    explanation: "Vì x > 0 và |x| = 7 nên x = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_049",
    problemStr: "Tìm x dương: |x - 2| = 6",
    correctAnswer: 8,
    emojiAnalogy: "x - 2 = 6 ➡️ x = 8 🎈",
    explanation: "Nghiệm dương: x - 2 = 6 ➡️ x = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_050",
    problemStr: "Tìm x dương: |x + 1| = 10",
    correctAnswer: 9,
    emojiAnalogy: "x + 1 = 10 ➡️ x = 9 🚀",
    explanation: "x + 1 = 10 ➡️ x = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },

  // --- TỈ LỆ THỨC & DÃY TỈ SỐ BẰNG NHAU (51 - 75) ---
  {
    id: "g7_051",
    problemStr: "Tìm x: x/4 = 6/8",
    correctAnswer: 3,
    emojiAnalogy: "x = (4 x 6) : 8 = 3 ⚖️",
    explanation: "Tỉ lệ thức: x = (4 x 6) / 8 = 24 / 8 = 3.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_052",
    problemStr: "Tìm x: x/3 = 12/4",
    correctAnswer: 9,
    emojiAnalogy: "x = 3 x 3 = 9 🌟",
    explanation: "12/4 = 3 ➡️ x = 3 x 3 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_053",
    problemStr: "Tìm x: x/5 = 8/10",
    correctAnswer: 4,
    emojiAnalogy: "x = (5 x 8) : 10 = 4 🍏",
    explanation: "x = 40 / 10 = 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_054",
    problemStr: "Tìm x: x/2 = 15/5",
    correctAnswer: 6,
    emojiAnalogy: "x = 2 x 3 = 6 🎲",
    explanation: "15/5 = 3 ➡️ x = 2 x 3 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_055",
    problemStr: "Tìm x: x/6 = 4/3",
    correctAnswer: 8,
    emojiAnalogy: "x = (6 x 4) : 3 = 8 ⚡",
    explanation: "x = 24 / 3 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_056",
    problemStr: "Tìm x: 2/x = 4/14",
    correctAnswer: 7,
    emojiAnalogy: "x = (2 x 14) : 4 = 7 🌸",
    explanation: "x = 28 / 4 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_057",
    problemStr: "Tìm x: x/7 = 8/14",
    correctAnswer: 4,
    emojiAnalogy: "x = (7 x 8) : 14 = 4 🚙",
    explanation: "x = 56 / 14 = 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_058",
    problemStr: "Tìm x: x/8 = 5/10",
    correctAnswer: 4,
    emojiAnalogy: "x = 8 x 1/2 = 4 🍰",
    explanation: "5/10 = 1/2 ➡️ x = 8 / 2 = 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_059",
    problemStr: "Tìm x: x/9 = 6/18",
    correctAnswer: 3,
    emojiAnalogy: "6/18 = 1/3 ➡️ x = 3 🍉",
    explanation: "x = 9 / 3 = 3.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_060",
    problemStr: "Tìm x: x/10 = 7/10",
    correctAnswer: 7,
    emojiAnalogy: "x = 7 🎯",
    explanation: "Hai phân số cùng mẫu thì x = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_061",
    problemStr: "Tìm x: x/3 = 18/6",
    correctAnswer: 9,
    emojiAnalogy: "18/6 = 3 ➡️ x = 3 x 3 = 9 🚀",
    explanation: "x = 3 x 3 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_062",
    problemStr: "Tìm x: 3/x = 9/15",
    correctAnswer: 5,
    emojiAnalogy: "x = (3 x 15) : 9 = 5 🖐️",
    explanation: "x = 45 / 9 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_063",
    problemStr: "Tìm x: 4/x = 12/18",
    correctAnswer: 6,
    emojiAnalogy: "x = (4 x 18) : 12 = 6 🎲",
    explanation: "x = 72 / 12 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_064",
    problemStr: "Tìm x: 5/x = 25/40",
    correctAnswer: 8,
    emojiAnalogy: "x = (5 x 40) : 25 = 8 ⚡",
    explanation: "x = 200 / 25 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Thử thách",
  },
  {
    id: "g7_065",
    problemStr: "Tìm x: 6/x = 18/27",
    correctAnswer: 9,
    emojiAnalogy: "x = (6 x 27) : 18 = 9 💎",
    explanation: "18/27 = 2/3 ➡️ x = 6 x 3 / 2 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_066",
    problemStr: "Tìm x: 7/x = 21/30",
    correctAnswer: 10,
    emojiAnalogy: "x = 10 🔟",
    explanation: "21/30 = 7/10 ➡️ x = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Trung bình",
  },
  {
    id: "g7_067",
    problemStr: "Bậc của đơn thức: 5x²y³",
    correctAnswer: 5,
    emojiAnalogy: "Bậc = 2 + 3 = 5 📊",
    explanation: "Bậc của đơn thức bằng tổng số mũ của các biến: 2 + 3 = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_068",
    problemStr: "Bậc của đơn thức: 3x⁴y²",
    correctAnswer: 6,
    emojiAnalogy: "4 + 2 = 6 📈",
    explanation: "Bậc = 4 + 2 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_069",
    problemStr: "Bậc của đơn thức: 7x³y⁴",
    correctAnswer: 7,
    emojiAnalogy: "3 + 4 = 7 🌸",
    explanation: "Bậc = 3 + 4 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_070",
    problemStr: "Bậc của đơn thức: 2x⁵y³",
    correctAnswer: 8,
    emojiAnalogy: "5 + 3 = 8 ⚡",
    explanation: "Bậc = 5 + 3 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_071",
    problemStr: "Bậc của đơn thức: 4x⁶y³",
    correctAnswer: 9,
    emojiAnalogy: "6 + 3 = 9 🌟",
    explanation: "Bậc = 6 + 3 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_072",
    problemStr: "Bậc của đơn thức: 9x⁵y⁵",
    correctAnswer: 10,
    emojiAnalogy: "5 + 5 = 10 🔟",
    explanation: "Bậc = 5 + 5 = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_073",
    problemStr: "Hệ số của đơn thức: 8x²y³",
    correctAnswer: 8,
    emojiAnalogy: "Hệ số = 8 🎈",
    explanation: "Hệ số là phần số đứng trước biến: 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_074",
    problemStr: "Hệ số của đơn thức: 9a²b",
    correctAnswer: 9,
    emojiAnalogy: "Hệ số = 9 💎",
    explanation: "Hệ số là 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_075",
    problemStr: "Hệ số của đơn thức: 7xy",
    correctAnswer: 7,
    emojiAnalogy: "Hệ số = 7 🎯",
    explanation: "Hệ số là 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },

  // --- HÌNH HỌC & ĐỊNH LÝ PYTHAGORE (76 - 100) ---
  {
    id: "g7_076",
    problemStr: "Pythagoras: Cạnh huyền Δ vuông cạnh 3 & 4 là?",
    correctAnswer: 5,
    emojiAnalogy: "c = √(3² + 4²) = √25 = 5 📐",
    explanation: "Định lý Pythagoras: c² = 3² + 4² = 9 + 16 = 25 ➡️ c = 5.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_077",
    problemStr: "Pythagoras: Cạnh huyền Δ vuông cạnh 6 & 8 là?",
    correctAnswer: 10,
    emojiAnalogy: "c = √(6² + 8²) = √100 = 10 🔟",
    explanation: "c² = 6² + 8² = 36 + 64 = 100 ➡️ c = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_078",
    problemStr: "Pythagoras: Cạnh góc vuông khi huyền = 5, cạnh kia = 3 là?",
    correctAnswer: 4,
    emojiAnalogy: "b = √(5² - 3²) = √16 = 4 ⏹️",
    explanation: "b² = 5² - 3² = 25 - 9 = 16 ➡️ b = 4.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_079",
    problemStr: "Pythagoras: Cạnh góc vuông khi huyền = 10, cạnh kia = 8 là?",
    correctAnswer: 6,
    emojiAnalogy: "a = √(10² - 8²) = √36 = 6 🎲",
    explanation: "a² = 100 - 64 = 36 ➡️ a = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_080",
    problemStr: "Pythagoras: Cạnh góc vuông khi huyền = 10, cạnh kia = 6 là?",
    correctAnswer: 8,
    emojiAnalogy: "b = √(10² - 6²) = √64 = 8 ⚡",
    explanation: "b² = 100 - 36 = 64 ➡️ b = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_081",
    problemStr: "Tổng ba góc trong một tam giác chia cho 20 là?",
    correctAnswer: 9,
    emojiAnalogy: "180° : 20 = 9 🌟",
    explanation: "Tổng 3 góc tam giác = 180°, 180 : 20 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_082",
    problemStr: "Mỗi góc trong tam giác đều chia cho 10 là?",
    correctAnswer: 6,
    emojiAnalogy: "60° : 10 = 6 🔺",
    explanation: "Tam giác đều mỗi góc 60°, 60 : 10 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_083",
    problemStr: "Tam giác vuông cân có góc nhọn chia cho 5 là?",
    correctAnswer: 9,
    emojiAnalogy: "45° : 5 = 9 🎯",
    explanation: "Góc nhọn của tam giác vuông cân là 45°, 45 : 5 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_084",
    problemStr: "Số đường trung tuyến trong một tam giác là?",
    correctAnswer: 3,
    emojiAnalogy: "3 đỉnh kẻ 3 đường trung tuyến 📐",
    explanation: "Một tam giác có đúng 3 đường trung tuyến cắt nhau tại trọng tâm.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g7_085",
    problemStr: "Số đường phân giác trong một tam giác là?",
    correctAnswer: 3,
    emojiAnalogy: "3 đường phân giác ✂️",
    explanation: "Mỗi tam giác có 3 đường phân giác.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g7_086",
    problemStr: "Số đường cao trong một tam giác là?",
    correctAnswer: 3,
    emojiAnalogy: "3 đường cao cắt nhau tại trực tâm 🏔️",
    explanation: "Tam giác có 3 đường cao.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Dễ",
  },
  {
    id: "g7_087",
    problemStr: "Trọng tâm tam giác cách đỉnh bằng mấy phần đường trung tuyến (mẫu là 3)?",
    correctAnswer: 2,
    emojiAnalogy: "2/3 độ dài trung tuyến ⚖️",
    explanation: "Trọng tâm cách đỉnh bằng 2/3 độ dài đường trung tuyến đi qua đỉnh đó.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Hình học & Pythagore",
    difficulty: "Trung bình",
  },
  {
    id: "g7_088",
    problemStr: "Giá trị biểu thức A = 2x + 1 tại x = 3 là?",
    correctAnswer: 7,
    emojiAnalogy: "2(3) + 1 = 6 + 1 = 7 🌸",
    explanation: "Thay x = 3: 2(3) + 1 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_089",
    problemStr: "Giá trị biểu thức B = 3x - 1 tại x = 3 là?",
    correctAnswer: 8,
    emojiAnalogy: "3(3) - 1 = 9 - 1 = 8 🍪",
    explanation: "3(3) - 1 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_090",
    problemStr: "Giá trị biểu thức C = x² - 1 tại x = 3 là?",
    correctAnswer: 8,
    emojiAnalogy: "3² - 1 = 9 - 1 = 8 ⚡",
    explanation: "9 - 1 = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_091",
    problemStr: "Giá trị biểu thức D = x² + 1 tại x = 3 là?",
    correctAnswer: 10,
    emojiAnalogy: "3² + 1 = 9 + 1 = 10 🔟",
    explanation: "9 + 1 = 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_092",
    problemStr: "Giá trị biểu thức 4x - 6 tại x = 3 là?",
    correctAnswer: 6,
    emojiAnalogy: "4(3) - 6 = 12 - 6 = 6 🎲",
    explanation: "12 - 6 = 6.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_093",
    problemStr: "Giá trị biểu thức 5x - 8 tại x = 3 là?",
    correctAnswer: 7,
    emojiAnalogy: "5(3) - 8 = 15 - 8 = 7 🍒",
    explanation: "15 - 8 = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_094",
    problemStr: "Giá trị biểu thức 6x - 9 tại x = 3 là?",
    correctAnswer: 9,
    emojiAnalogy: "6(3) - 9 = 18 - 9 = 9 🚀",
    explanation: "18 - 9 = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Dễ",
  },
  {
    id: "g7_095",
    problemStr: "Số đối của số -8 là?",
    correctAnswer: 8,
    emojiAnalogy: "-(-8) = 8 🎈",
    explanation: "Số đối của -8 là 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_096",
    problemStr: "Số đối của số -9 là?",
    correctAnswer: 9,
    emojiAnalogy: "-(-9) = 9 💎",
    explanation: "Số đối của -9 là 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_097",
    problemStr: "Số đối của số -10 là?",
    correctAnswer: 10,
    emojiAnalogy: "-(-10) = 10 🔟",
    explanation: "Số đối của -10 là 10.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tỉ lệ thức & Số hữu tỉ",
    difficulty: "Dễ",
  },
  {
    id: "g7_098",
    problemStr: "Nghiệm của đa thức P(x) = 2x - 14 là?",
    correctAnswer: 7,
    emojiAnalogy: "2x = 14 ➡️ x = 7 🎯",
    explanation: "2x - 14 = 0 ➡️ x = 7.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g7_099",
    problemStr: "Nghiệm của đa thức Q(x) = 3x - 24 là?",
    correctAnswer: 8,
    emojiAnalogy: "3x = 24 ➡️ x = 8 ⚡",
    explanation: "3x - 24 = 0 ➡️ x = 8.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
  {
    id: "g7_100",
    problemStr: "Nghiệm của đa thức H(x) = 4x - 36 là?",
    correctAnswer: 9,
    emojiAnalogy: "4x = 36 ➡️ x = 9 🌟",
    explanation: "4x - 36 = 0 ➡️ x = 9.",
    gradeLevel: "Lớp 7 (THCS)",
    topic: "Tìm x & Đại số",
    difficulty: "Trung bình",
  },
];
